T = {
# --- privacidade ---
'Política de privacidade | Estudatta': 'Privacy policy | Estudatta',
'Como o Estudatta trata seus dados': 'How Estudatta handles your data',
'Esta página explica, em linguagem direta, quais dados o serviço coleta, para que os usa, com quem os compartilha e como você exporta ou apaga tudo. Ela descreve o que o serviço faz — não é um atestado de conformidade.': 'This page explains, in plain language, what data the service collects, what it is used for, who it is shared with and how you export or delete everything. It describes what the service does — it is not a certificate of compliance.',
'Última atualização: 21 de setembro de 2026': 'Last updated: September 21, 2026',
'Última atualização: 18 de setembro de 2026': 'Last updated: September 18, 2026',
'Informações pendentes do responsável.': 'Information pending from the controller.',
'Este documento descreve o comportamento implementado no serviço. Os itens abaixo aparecem marcados em damasco e devem ser preenchidos antes da publicação: razão social e CNPJ do responsável; endereço; nome e e-mail do encarregado (DPO); prazo de retenção dos registros operacionais; identificação do provedor de armazenamento de arquivos e do provedor de IA em produção.': 'This document describes the behavior implemented in the service. The items below are highlighted in apricot and must be filled in before publication: the controller’s legal name and tax ID (CNPJ); address; name and email of the data protection officer (DPO); retention period for operational records; the file storage provider and the AI provider in production.',
'Sumário': 'Contents',
'Quem é o responsável e a que esta política se aplica': 'Who the controller is and what this policy applies to',
'Quais dados coletamos': 'What data we collect',
'Para que usamos os dados': 'What we use the data for',
'Cookies e armazenamento no aparelho': 'Cookies and on-device storage',
'Com quem os dados são compartilhados': 'Who the data is shared with',
'Recursos de IA (opcionais)': 'AI features (optional)',
'Materiais enviados e importação': 'Uploaded materials and import',
'Por quanto tempo guardamos': 'How long we keep it',
'Seus direitos: exportar, corrigir e excluir': 'Your rights: export, correct and delete',
'Segurança': 'Security',
'Alterações desta política': 'Changes to this policy',
'Contato e encarregado': 'Contact and data protection officer',
'O Estudatta é operado por': 'Estudatta is operated by',
'[razão social a definir pelo responsável]': '[legal name to be defined by the controller]',
', CNPJ': ', CNPJ (Brazilian tax ID)',
'[a definir pelo responsável]': '[to be defined by the controller]',
', com endereço em': ', with address at',
'(“nós”). Esta política se aplica ao site': '(“we”). This policy applies to the website',
'estudatta.com.br': 'estudatta.com.br',
', ao aplicativo web que ele hospeda e à API que o atende.': ', to the web application it hosts and to the API that serves it.',
'O serviço é um planejador de estudo e prática: você define um objetivo, uma meta de tempo e os dias da semana; o serviço organiza o plano, registra as sessões e transforma o que faltou em tempo a recuperar. Tratamos dados pessoais para prestar exatamente isso, conforme a Lei Geral de Proteção de Dados (Lei nº 13.709/2018).': 'The service is a study and practice planner: you set a goal, a time target and the days of the week; the service organizes the plan, logs the sessions and turns what was missed into time to make up. We process personal data to provide exactly that, in accordance with Brazil’s General Data Protection Law (LGPD, Law No. 13,709/2018).',
'Dados da conta': 'Account data',
'(obrigatório; usado como identificador de acesso e para os e-mails descritos na seção 3).': '(required; used as the login identifier and for the emails described in section 3).',
'Nome': 'Name',
'(opcional) e': '(optional) and',
'fuso horário': 'time zone',
'(padrão América/São Paulo), usados para montar o plano no seu horário local. Idioma da interface (padrão pt-BR).': '(default America/Sao_Paulo), used to build the plan in your local time. Interface language (default pt-BR).',
'Senha': 'Password',
', armazenada apenas como hash criptográfico. Nunca guardamos a senha em texto.': ', stored only as a cryptographic hash. We never store the password in plain text.',
'Se você entrar com Google (quando esse login estiver habilitado): o identificador da sua conta Google, o e-mail e o nome informados pelo Google. Não recebemos sua senha do Google.': 'If you sign in with Google (when that login is enabled): your Google account identifier, the email and the name provided by Google. We do not receive your Google password.',
'Datas de criação da conta, de confirmação do e-mail e do último acesso.': 'Dates of account creation, email confirmation and last access.',
'Dados que você cria ao usar o serviço': 'Data you create while using the service',
'Objetivos (título, descrição, categoria, resultado desejado, datas, prazo da prova, dias e horários disponíveis), regras de meta e pausas planejadas (com o motivo, se você escrever um).': 'Goals (title, description, category, desired outcome, dates, exam deadline, available days and times), goal rules and planned breaks (with the reason, if you write one).',
'Matérias, tópicos, tarefas e materiais: títulos, descrições, links, intervalos de páginas, posição de leitura e os arquivos PDF que você enviar.': 'Subjects, topics, tasks and materials: titles, descriptions, links, page ranges, reading position and the PDF files you upload.',
'Sessões de estudo: início, fim, duração, tópico, páginas, observações em texto livre, configuração de pomodoro, fuso horário e o identificador do aparelho em que foram registradas.': 'Study sessions: start, end, duration, topic, pages, free-text notes, pomodoro settings, time zone and the identifier of the device they were logged on.',
'Preferências: tema, tom das mensagens (acolhedor, direto ou firme), primeiro dia da semana, duração padrão de sessão, movimento reduzido, e a sua resposta sobre consentimento para métricas de uso (sim, não ou sem resposta).': 'Preferences: theme, message tone (warm, direct or firm), first day of the week, default session length, reduced motion, and your answer about consent to usage metrics (yes, no or no answer).',
'Preferências de lembretes: canais (aplicativo, push, e-mail), horários, dias, horário de silêncio, limite diário e se o nome do objetivo aparece na notificação (por padrão, não aparece).': 'Reminder preferences: channels (app, push, email), times, days, quiet hours, daily limit and whether the goal name appears in the notification (by default it does not).',
'Dados técnicos e de segurança': 'Technical and security data',
'Para cada sessão de acesso: endereço IP, identificação do navegador (até 300 caracteres), um rótulo do tipo de aparelho (“iPhone/iPad”, “Android”, “Windows”, “Mac”, “Linux” ou “Navegador”), data de criação, de expiração e do último uso.': 'For each login session: IP address, browser identification (up to 300 characters), a device type label (“iPhone/iPad”, “Android”, “Windows”, “Mac”, “Linux” or “Browser”), creation, expiration and last-use dates.',
'Um identificador aleatório do aparelho, gerado pelo próprio navegador e enviado em cada requisição, usado para sincronizar o registro feito sem internet e evitar duplicidade.': 'A random device identifier, generated by the browser itself and sent with every request, used to sync logs made offline and avoid duplicates.',
'Registros de auditoria de ações sensíveis (criação de conta, entrada, troca de senha, exclusão da conta, envio e exclusão de materiais, importações, assinatura de push, ações de cobrança e ações administrativas), com data, IP e identificador da requisição.': 'Audit records of sensitive actions (account creation, sign-in, password change, account deletion, material upload and deletion, imports, push subscription, billing actions and administrative actions), with date, IP and request identifier.',
'Fila de notificações e resultado das entregas. Nos registros de entrega de push guardamos apenas um resumo criptográfico do endereço da assinatura, não o endereço em si.': 'Notification queue and delivery results. In push delivery records we keep only a cryptographic digest of the subscription address, not the address itself.',
'Contato e novidades': 'Contact and updates',
'Se você usar o formulário de': 'If you use the',
', guardamos nome (opcional), e-mail, assunto e mensagem. Se deixar o e-mail para receber novidades, guardamos o e-mail e a origem do cadastro.': ' form, we keep name (optional), email, subject and message. If you leave your email to receive updates, we keep the email and where you signed up.',
'Pagamento (quando a cobrança estiver habilitada)': 'Payment (when billing is enabled)',
'Guardamos o plano contratado, os identificadores da assinatura e do pagador atribuídos pelo processador de pagamento, o status, o período vigente, o valor e a moeda, além dos eventos que o processador nos envia sobre a assinatura.': 'We keep the plan subscribed, the subscription and payer identifiers assigned by the payment processor, the status, the current period, the amount and currency, plus the events the processor sends us about the subscription.',
'Nunca recebemos nem armazenamos número de cartão, código de segurança, CPF ou endereço de cobrança': 'We never receive or store card numbers, security codes, tax IDs or billing addresses',
': o pagamento é concluído no ambiente do processador (seção 5).': ': payment is completed in the processor’s environment (section 5).',
'O que não coletamos': 'What we do not collect',
'Não coletamos localização, contatos, câmera ou microfone. Não usamos, hoje, nenhum serviço de métricas de uso, pixel de rastreamento ou cookie de terceiros no site ou no aplicativo.': 'We do not collect location, contacts, camera or microphone. In the app, we use no usage-metrics service, tracking pixel or third-party cookie; on the website, Google Analytics runs only with your consent (section 4).',
'Prestar o serviço': 'Providing the service',
': calcular a meta de hoje, o saldo, a pendência e a recuperação sugerida; manter o plano sincronizado entre seus aparelhos; funcionar sem internet e sincronizar depois. Base legal: execução do contrato.': ': calculating today’s goal, the balance, owed time and suggested catch-up; keeping the plan in sync across your devices; working offline and syncing later. Legal basis: performance of the contract.',
'E-mails transacionais': 'Transactional emails',
': existem apenas três — confirmação de e-mail (link válido por 24 horas), redefinição de senha (link válido por 1 hora) e o resumo semanal, que só é enviado se você ativar o canal de e-mail e o resumo semanal nas preferências (ambos desligados por padrão). Não enviamos e-mail de marketing.': ': there are only three — email confirmation (link valid for 24 hours), password reset (link valid for 1 hour) and the weekly summary, which is only sent if you enable the email channel and the weekly summary in preferences (both off by default). We do not send marketing email.',
': notificações dentro do aplicativo e, se você permitir no navegador, notificações push (seção 5). O serviço limita a quantidade diária, respeita o horário de silêncio e cancela lembretes que perderam o sentido (por exemplo, quando a sessão já foi registrada). Base legal: consentimento, revogável nas preferências.': ': in-app notifications and, if you allow it in the browser, push notifications (section 5). The service limits the daily amount, respects quiet hours and cancels reminders that no longer make sense (for example, when the session has already been logged). Legal basis: consent, revocable in preferences.',
': limitar tentativas de entrada e de recuperação de senha, detectar uso indevido, manter registros de auditoria e permitir que você veja e encerre sessões em outros aparelhos. Base legal: legítimo interesse e cumprimento de obrigações legais.': ': limiting sign-in and password recovery attempts, detecting misuse, keeping audit records and letting you see and end sessions on other devices. Legal basis: legitimate interest and compliance with legal obligations.',
'Cobrança': 'Billing',
'(quando habilitada): iniciar, acompanhar e cancelar a assinatura e aplicar os limites do plano. Base legal: execução do contrato.': '(when enabled): starting, tracking and cancelling the subscription and applying plan limits. Legal basis: performance of the contract.',
'Atendimento': 'Support',
': responder às mensagens enviadas pelo formulário de contato, no e-mail que você informar.': ': replying to messages sent through the contact form, at the email you provide.',
'Recursos de IA': 'AI features',
', apenas quando habilitados e apenas quando você pedir (seção 6). Base legal: consentimento, manifestado a cada ação.': ', only when enabled and only when you ask (section 6). Legal basis: consent, given with each action.',
'Não vendemos dados pessoais e não usamos seus dados para publicidade.': 'We do not sell personal data and we do not use your data for advertising.',
'Cookie de sessão': 'Session cookie',
': próprio (primeira parte),': ': first-party,',
'(inacessível a scripts),': '(inaccessible to scripts),',
', marcado como seguro em produção, válido por': ', marked secure in production, valid for',
'. Contém apenas um identificador aleatório; o servidor guarda somente o hash dele. É apagado ao sair ou ao encerrar a sessão.': '. It contains only a random identifier; the server keeps only its hash. It is deleted when you sign out or end the session.',
'Google Analytics 4 (só neste site, estudatta.com.br)': 'Google Analytics 4 (on this website only, estudatta.com.br)',
': mede quais páginas do site são visitadas e de onde vêm as visitas. Só é ativado depois que você aceita no aviso de cookies; se recusar ou não responder, nenhum script nem cookie do Google é carregado. A escolha fica no seu navegador por 12 meses e pode ser mudada pelo link “Cookies” no rodapé. O Google trata os dados conforme a política dele; não usamos os dados para publicidade.': ': measures which pages of the site are visited and where visits come from. It is only activated after you accept in the cookie notice; if you decline or don’t answer, no Google script or cookie is loaded. Your choice is kept in your browser for 12 months and can be changed through the “Cookies” link in the footer. Google processes the data under its own policy; we do not use the data for advertising.',
'O aplicativo': 'The app',
'(app.estudatta.com.br) não tem Google Analytics nem cookies de terceiros.': '(app.estudatta.com.br) has no Google Analytics and no third-party cookies.',
'Armazenamento local do navegador': 'Browser local storage',
'(localStorage e IndexedDB): identificador do aparelho, tema escolhido, data da última sincronização, um instantâneo da tela Hoje, o plano sincronizado, a fila de registros feitos sem internet e o estado do cronômetro. Serve para o aplicativo abrir e funcionar sem conexão.': '(localStorage and IndexedDB): device identifier, chosen theme, date of last sync, a snapshot of the Today screen, the synced plan, the queue of logs made offline and the timer state. It lets the app open and work without a connection.',
'Nunca guarda senha nem credenciais.': 'It never stores passwords or credentials.',
'Você apaga tudo isso limpando os dados do site no navegador.': 'You delete all of it by clearing the site data in your browser.',
'Token contra falsificação de requisições (CSRF)': 'Cross-site request forgery (CSRF) token',
': entregue ao aplicativo ao entrar e enviado em cabeçalho a cada alteração; não é cookie.': ': handed to the app at sign-in and sent in a header with every change; it is not a cookie.',
'Métricas de uso': 'Usage metrics',
': não há nenhum provedor habilitado hoje. Se um for habilitado no futuro, será carregado apenas com o seu consentimento, registrado na preferência correspondente da sua conta, e esta política será atualizada com o nome do provedor.': ': in the app, no provider is enabled today. If one is enabled in the future, it will be loaded only with your consent, recorded in the corresponding preference of your account, and this policy will be updated with the provider’s name.',
'Compartilhamos dados apenas com operadores necessários ao funcionamento do serviço, cada um limitado ao mínimo. Todos abaixo são opcionais e dependem de configuração do ambiente:': 'We share data only with processors needed for the service to work, each limited to the minimum. All of the following are optional and depend on the environment configuration:',
'Asaas': 'Asaas',
'(processamento de pagamento, quando a cobrança estiver habilitada): recebe do Estudatta a descrição do plano, o valor, a periodicidade e uma referência aleatória sem dados pessoais. Nome, CPF, e-mail e dados do cartão você informa direto na página de pagamento do Asaas; o Estudatta não recebe nem guarda esses dados. O pagamento em si acontece no site do Asaas, sob a política de privacidade dele.': '(payment processing, when billing is enabled): receives from Estudatta the plan description, the amount, the billing period and a random reference with no personal data. Name, tax ID, email and card details you enter directly on Asaas’s payment page; Estudatta neither receives nor stores that data. The payment itself happens on Asaas’s website, under its privacy policy.',
'Provedor de IA': 'AI provider',
'(quando os recursos de IA estiverem habilitados): recebe apenas o trecho necessário à ação que você pediu, conforme a seção 6. Provedor em produção:': '(when AI features are enabled): receives only the excerpt needed for the action you requested, as described in section 6. Provider in production:',
'Serviços de notificação push do navegador': 'Browser push notification services',
'(operados pelo fabricante do navegador ou do sistema, como os do Google, da Mozilla e da Apple): recebem o conteúdo da notificação, criptografado para a sua assinatura. Só acontece se você permitir notificações.': '(operated by the browser or operating system vendor, such as Google, Mozilla and Apple): receive the notification content, encrypted for your subscription. This only happens if you allow notifications.',
'Google': 'Google',
'(apenas se você escolher entrar com Google): troca de identificação conforme o protocolo OpenID Connect, com os escopos e-mail e perfil.': '(only if you choose to sign in with Google): identity exchange under the OpenID Connect protocol, with the email and profile scopes.',
'Servidor de e-mail (SMTP)': 'Email server (SMTP)',
'configurado pelo responsável, para os três e-mails transacionais. Remetente: no-reply@estudatta.com.br.': 'configured by the controller, for the three transactional emails. Sender: no-reply@estudatta.com.br.',
'Armazenamento de arquivos': 'File storage',
'para os PDFs enviados: disco próprio ou serviço compatível com S3, em área privada. Provedor em produção:': 'for uploaded PDFs: own disk or an S3-compatible service, in a private area. Provider in production:',
'Fora isso, dados só são compartilhados por obrigação legal ou ordem de autoridade competente.': 'Beyond that, data is only shared under legal obligation or an order from a competent authority.',
'Os recursos de IA vêm': 'AI features come',
'desligados por padrão': 'off by default',
'. Quando desligados, o aplicativo informa isso e você organiza tudo manualmente.': '. When off, the app tells you so and you organize everything manually.',
'Quando habilitados, só são acionados por': 'When enabled, they are only triggered by',
'ação explícita sua': 'your explicit action',
', em três situações: sugerir a estrutura de matérias e tópicos a partir de um texto ou de uma importação; sugerir uma distribuição de plano; redigir o resumo da semana. Nada roda em segundo plano.': ', in three situations: suggesting the subject and topic structure from a text or an import; suggesting a plan distribution; writing the weekly summary. Nothing runs in the background.',
'O que é enviado': 'What is sent',
': apenas o trecho necessário — o texto que você colou ou extraiu (limitado a 60 mil caracteres, com aviso quando houver corte), ou o título do objetivo e os números do período (minutos, dias, pendência), ou os títulos dos tópicos e a disponibilidade dos dias. Não enviamos seu e-mail, nome ou identificadores de conta. O texto é enviado como dado a ser analisado, com instrução para não ser interpretado como comando.': ': only the necessary excerpt — the text you pasted or extracted (limited to 60,000 characters, with a warning when truncated), or the goal title and the period’s numbers (minutes, days, owed time), or the topic titles and the days’ availability. We do not send your email, name or account identifiers. The text is sent as data to be analyzed, with instructions not to interpret it as commands.',
'O que guardamos': 'What we keep',
': nos nossos registros de uso ficam apenas contadores — ação, modelo, quantidade de caracteres e de tokens, tempo de resposta e código de erro. Não registramos o conteúdo enviado nem a resposta.': ': our usage records hold only counters — action, model, number of characters and tokens, response time and error code. We do not record the content sent or the response.',
'Toda resposta é prévia': 'Every answer is a preview',
': nada muda no seu plano até você revisar e confirmar. A resposta é validada e o resumo semanal passa por um filtro que barra promessas e culpa.': ': nothing in your plan changes until you review and confirm. The answer is validated and the weekly summary goes through a filter that blocks promises and guilt.',
'Há limites diários por plano e um limite global; quando esgotados, o aplicativo avisa e nada é enviado.': 'There are daily limits per plan and a global limit; when exhausted, the app tells you and nothing is sent.',
'Aceitamos apenas arquivos': 'We accept only',
'PDF': 'PDF',
', verificados pelo conteúdo (não só pela extensão), de até': ' files, verified by content (not just extension), of up to',
'25 MB': '25 MB',
'e': 'and',
'800 páginas': '800 pages',
'. Você também pode cadastrar links (somente https) e livros físicos sem enviar arquivo.': '. You can also add links (https only) and physical books without uploading a file.',
'Os arquivos ficam em área privada, identificados pela sua conta. Para abrir ou baixar, o aplicativo gera um link assinado que expira em': 'Files are kept in a private area, tied to your account. To open or download, the app generates a signed link that expires in',
'10 minutos': '10 minutes',
'Na importação de conteúdo programático (texto colado, CSV ou PDF), extraímos apenas a camada de texto do PDF e guardamos esse texto junto com a proposta de matérias e tópicos, para que você revise.': 'When importing a syllabus (pasted text, CSV or PDF), we extract only the PDF’s text layer and keep that text together with the proposed subjects and topics, for you to review.',
'Não fazemos OCR': 'We do not do OCR',
': PDFs digitalizados como imagem são recusados com aviso. Nada é criado sem a sua confirmação.': ': PDFs scanned as images are rejected with a warning. Nothing is created without your confirmation.',
'Excluir um material apaga o arquivo do armazenamento. Excluir a conta apaga todos os seus arquivos.': 'Deleting a material removes the file from storage. Deleting the account removes all your files.',
'Você é responsável por ter o direito de usar os arquivos que envia; não os analisamos nem os compartilhamos com terceiros além do descrito na seção 5.': 'You are responsible for having the right to use the files you upload; we do not analyze them or share them with third parties beyond what is described in section 5.',
'Dados da conta e conteúdo de estudo': 'Account data and study content',
': enquanto a conta existir. Ao excluir a conta, são apagados imediatamente (seção 9).': ': for as long as the account exists. When you delete the account, they are deleted immediately (section 9).',
'Sessões de acesso expiradas e tokens de uso único': 'Expired login sessions and single-use tokens',
': apagados automaticamente 7 dias após expirar.': ': deleted automatically 7 days after expiring.',
'Fila de notificações e registros de entrega': 'Notification queue and delivery records',
': apagados automaticamente após 90 dias.': ': deleted automatically after 90 days.',
'Registros operacionais': 'Operational records',
'— auditoria de ações, eventos recebidos do processador de pagamento, contadores de uso de IA, mensagens de contato, cadastro para novidades e fila de sincronização —: mantidos por': '— action audit, events received from the payment processor, AI usage counters, contact messages, updates sign-up and sync queue —: kept for',
'[período a definir pelo responsável]': '[period to be defined by the controller]',
', de forma anonimizada após a exclusão da conta.': ', anonymized after the account is deleted.',
'Dados fiscais e de cobrança': 'Tax and billing data',
'exigidos por lei: pelo prazo legal aplicável.': 'required by law: for the applicable legal period.',
'Você exerce a maior parte dos direitos diretamente no aplicativo, sem pedir a ninguém:': 'You exercise most of your rights directly in the app, without asking anyone:',
'Acesso e portabilidade': 'Access and portability',
': em Preferências, exporte tudo em JSON (conta, objetivos, matérias, tópicos, materiais, tarefas, sessões) ou o histórico de sessões em CSV. Os PDFs enviados podem ser baixados um a um pela tela de materiais. A exportação': ': in Preferences, export everything as JSON (account, goals, subjects, topics, materials, tasks, sessions) or the session history as CSV. Uploaded PDFs can be downloaded one by one from the materials screen. Export',
'não depende de assinatura': 'does not depend on a subscription',
'Correção': 'Correction',
': edite nome, fuso horário, idioma, preferências e todo o conteúdo de estudo a qualquer momento.': ': edit name, time zone, language, preferences and all study content at any time.',
'Exclusão': 'Deletion',
': em Preferências, confirme a exclusão da conta digitando a palavra pedida e, se houver senha, a senha. A exclusão é': ': in Preferences, confirm account deletion by typing the requested word and, if there is a password, the password. Deletion is',
'imediata e irreversível': 'immediate and irreversible',
': apaga conta, objetivos, sessões, materiais (inclusive os arquivos), notificações, assinaturas de push, preferências e importações. Permanecem apenas registros de auditoria, contadores de uso de IA e eventos de cobrança,': ': it deletes the account, goals, sessions, materials (including files), notifications, push subscriptions, preferences and imports. Only audit records, AI usage counters and billing events remain,',
'sem vínculo com a sua identidade': 'with no link to your identity',
'. Exporte antes se quiser guardar uma cópia.': '. Export first if you want to keep a copy.',
'Revogar consentimentos': 'Withdraw consent',
': desative push, e-mail e resumo semanal nas preferências de lembretes; não use os recursos de IA; encerre sessões em outros aparelhos na tela de sessões.': ': turn off push, email and the weekly summary in reminder preferences; don’t use the AI features; end sessions on other devices from the sessions screen.',
'Cancelar a assinatura': 'Cancel the subscription',
'(quando houver): na tela de planos, sem obstáculos. Cancelar não apaga nada.': '(when there is one): on the plans screen, with no hurdles. Cancelling deletes nothing.',
'Para pedidos que o aplicativo não cobre (por exemplo, informação sobre compartilhamentos específicos ou oposição a um tratamento), escreva para': 'For requests the app doesn’t cover (for example, information about specific sharing or objection to a processing activity), write to',
'. Você também pode apresentar reclamação à Autoridade Nacional de Proteção de Dados (ANPD).': '. You can also file a complaint with Brazil’s National Data Protection Authority (ANPD).',
'Senhas armazenadas com hash de propósito específico; mínimo de 8 caracteres.': 'Passwords stored with a purpose-built hash; minimum of 8 characters.',
'Tokens de confirmação e de redefinição de senha aleatórios, de uso único, guardados apenas como hash; redefinir a senha encerra todas as sessões abertas.': 'Random, single-use confirmation and password reset tokens, stored only as hashes; resetting the password ends all open sessions.',
'Cookie de sessão HttpOnly, verificação de origem e token CSRF em toda alteração; limites de tentativas por endereço e por conta.': 'HttpOnly session cookie, origin checks and a CSRF token on every change; attempt limits per address and per account.',
'Cabeçalhos de proteção do navegador em todas as respostas e proibição de cache nas respostas da API.': 'Browser protection headers on every response and no caching of API responses.',
'Área administrativa restrita, com todas as ações auditadas. Não existe — nem existirá — “entrar como usuário”: a administração vê apenas totais agregados, nunca o conteúdo do seu estudo, suas notas ou seus arquivos.': 'A restricted admin area, with every action audited. There is no — and will be no — “sign in as user”: administration sees only aggregate totals, never your study content, notes or files.',
'Nenhum sistema é infalível. Se identificarmos um incidente que afete seus dados, comunicaremos você e as autoridades conforme a lei exigir. Esta seção descreve medidas adotadas; ela não afirma certificação ou auditoria externa.': 'No system is infallible. If we identify an incident affecting your data, we will notify you and the authorities as the law requires. This section describes measures taken; it does not claim certification or external audit.',
'A versão vigente é a publicada nesta página, com a data indicada no topo. Se uma alteração ampliar o uso dos seus dados ou habilitar um novo operador (por exemplo, métricas de uso ou um provedor de IA), avisaremos dentro do aplicativo antes de ela passar a valer.': 'The current version is the one published on this page, with the date shown at the top. If a change expands the use of your data or enables a new processor (for example, usage metrics or an AI provider), we will notify you inside the app before it takes effect.',
'Dúvidas, pedidos e reclamações sobre dados pessoais:': 'Questions, requests and complaints about personal data:',
'ou o': 'or the',
'formulário de contato': 'contact form',
'Encarregado pelo tratamento de dados pessoais (DPO):': 'Data protection officer (DPO):',
'[nome e e-mail a definir pelo responsável]': '[name and email to be defined by the controller]',
'Política de privacidade do Estudatta: quais dados o app de estudos coleta, como usa, com quem compartilha, cookies, IA, retenção e seus direitos pela LGPD.': 'Estudatta privacy policy: what data the study app collects, how it is used, who it is shared with, cookies, AI, retention and your rights under Brazil’s LGPD.',
'política de privacidade estudatta, lgpd estudatta, dados app de estudos': 'estudatta privacy policy, lgpd, study app data',
'Política de privacidade — Estudatta': 'Privacy policy — Estudatta',
# --- termos ---
'Termos de uso | Estudatta': 'Terms of use | Estudatta',
'Termos de uso': 'Terms of use',
'Termos de uso do Estudatta': 'Estudatta terms of use',
'O combinado entre você e o serviço: o que ele faz, o que não promete, como funcionam conta, planos, cobrança e encerramento. Escrito para ser lido inteiro em poucos minutos.': 'The agreement between you and the service: what it does, what it doesn’t promise, how account, plans, billing and termination work. Written to be read in full in a few minutes.',
'Este documento descreve o comportamento implementado no serviço. Os itens abaixo aparecem marcados em damasco e devem ser preenchidos antes da publicação: razão social, CNPJ e endereço do responsável; idade mínima para criar conta; política de reembolso; foro para solução de conflitos.': 'This document describes the behavior implemented in the service. The items below are highlighted in apricot and must be filled in before publication: the controller’s legal name, tax ID (CNPJ) and address; minimum age to create an account; refund policy; venue for dispute resolution.',
'Aceitação e partes': 'Acceptance and parties',
'O que o serviço é — e o que não é': 'What the service is — and what it is not',
'Conta e acesso': 'Account and access',
'Planos, preços e cobrança': 'Plans, prices and billing',
'Seu conteúdo e seus arquivos': 'Your content and your files',
'Uso aceitável': 'Acceptable use',
'Lembretes e notificações': 'Reminders and notifications',
'Disponibilidade e mudanças no serviço': 'Availability and changes to the service',
'Encerramento da conta': 'Account termination',
'Responsabilidade': 'Liability',
'Lei aplicável e foro': 'Governing law and venue',
'Estes termos regem o uso do site': 'These terms govern the use of the website',
', do aplicativo web que ele hospeda e da API que o atende (em conjunto, o “serviço”), operados por': ', the web application it hosts and the API that serves it (together, the “service”), operated by',
'(“nós”).': '(“we”).',
'Ao criar uma conta ou usar o serviço, você concorda com estes termos e com a': 'By creating an account or using the service, you agree to these terms and to the',
'. Se não concordar, não use o serviço.': '. If you do not agree, do not use the service.',
'O Estudatta é um planejador de estudo e prática. Você define um objetivo, uma meta de tempo por dia, os dias da semana e, se quiser, matérias, tópicos, materiais e tarefas. O serviço organiza o plano, registra as sessões (por cronômetro ou registro manual), calcula o saldo do dia e transforma o que faltou em tempo a recuperar, pela regra que você escolher.': 'Estudatta is a study and practice planner. You set a goal, a time target per day, the days of the week and, if you like, subjects, topics, materials and tasks. The service organizes the plan, logs the sessions (by timer or manual entry), calculates the day’s balance and turns what was missed into time to make up, by the rule you choose.',
'O serviço não:': 'The service does not:',
'ensina idiomas, oferece conteúdo de concurso, questões, aulas ou correção;': 'teach languages or offer exam content, questions, lessons or grading;',
'garante aprovação, fluência, nota, domínio de conteúdo ou o fim da procrastinação;': 'guarantee passing, fluency, grades, mastery of content or the end of procrastination;',
'avalia aprendizado: os relatórios medem': 'assess learning: the reports measure',
'constância e tempo': 'consistency and time',
', e só isso;': ', and only that;',
'substitui orientação pedagógica, médica ou psicológica.': 'replace educational, medical or psychological guidance.',
'Os resultados do seu estudo dependem do seu material, do seu método e de você.': 'The results of your studying depend on your material, your method and you.',
'Para usar o aplicativo é preciso criar uma conta com um e-mail válido e uma senha de pelo menos 8 caracteres, ou entrar com Google quando esse login estiver disponível. Enviamos um e-mail de confirmação; a confirmação pode ser exigida para entrar.': 'To use the app you need to create an account with a valid email and a password of at least 8 characters, or sign in with Google when that login is available. We send a confirmation email; confirmation may be required to sign in.',
'Idade mínima para criar conta:': 'Minimum age to create an account:',
'A conta é pessoal. Você é responsável por manter a senha em sigilo e por tudo o que for feito com ela. Na tela de sessões você vê os aparelhos conectados e pode encerrar qualquer um deles; trocar a senha encerra as demais sessões.': 'The account is personal. You are responsible for keeping the password secret and for everything done with it. On the sessions screen you see the connected devices and can end any of them; changing the password ends the other sessions.',
'Por segurança, limitamos tentativas de entrada, de confirmação e de recuperação de senha; ao exceder o limite, o serviço pede que você aguarde.': 'For security, we limit sign-in, confirmation and password recovery attempts; when the limit is exceeded, the service asks you to wait.',
'Informe dados verdadeiros. Podemos suspender contas usadas de forma fraudulenta ou abusiva (seção 6).': 'Provide truthful information. We may suspend accounts used fraudulently or abusively (section 6).',
'Plano gratuito': 'Free plan',
'O plano gratuito não exige cartão e não tem prazo. Ele inclui um objetivo ativo por vez, cronômetro e registro manual, plano semanal e pendências, lembretes básicos e as cotas de materiais informadas na': 'The free plan requires no card and has no time limit. It includes one active goal at a time, timer and manual logging, weekly plan and owed time, basic reminders and the material quotas listed on the',
'página de planos': 'plans page',
'Plano Completo': 'Complete plan',
'Os planos pagos (Essencial e Completo) são assinaturas mensais ou anuais. Recursos, limites e preços são os publicados na': 'The paid plans (Essential and Complete) are monthly or yearly subscriptions. Features, limits and prices are those published on the',
'no momento da contratação; enquanto o preço não estiver definido, a assinatura não está disponível e nenhuma cobrança acontece.': 'at the time of subscribing; while a price is not set, the subscription is unavailable and no charge is made.',
'O pagamento é processado pelo': 'Payment is processed by',
', na página de pagamento dele, quando a cobrança estiver habilitada. A assinatura é renovada automaticamente no cartão até você cancelar. Não recebemos nem guardamos dados de cartão. A assinatura passa a valer quando o processador confirma o pagamento.': ', on its payment page, when billing is enabled. The subscription renews automatically on the card until you cancel. We do not receive or store card details. The subscription takes effect when the processor confirms the payment.',
'Não há cobrança por minuto estudado, por sessão ou por objetivo': 'There is no charge per minute studied, per session or per goal',
': o valor é fixo pelo período contratado, use você o serviço muito ou pouco.': ': the price is fixed for the period subscribed, whether you use the service a lot or a little.',
'A renovação é automática ao fim de cada período, até você cancelar. Se o pagamento de uma renovação falhar, o serviço concede alguns dias de tolerância e depois volta a conta ao plano gratuito, sem apagar nada.': 'Renewal is automatic at the end of each period, until you cancel. If a renewal payment fails, the service grants a few days of grace and then returns the account to the free plan, without deleting anything.',
'Se o preço mudar, a alteração vale apenas para renovações futuras, nunca para o período já pago.': 'If the price changes, the change applies only to future renewals, never to the period already paid.',
'Cancelamento': 'Cancellation',
'Você pode cancelar a qualquer momento, na tela de planos, sem etapas de retenção ou justificativa. O acesso ao plano pago continua até o fim do período já pago e não há nova cobrança.': 'You can cancel at any time, on the plans screen, without retention steps or justification. Access to the paid plan continues until the end of the period already paid and there is no further charge.',
'Ao voltar ao plano gratuito, nada é apagado. Se você tiver mais objetivos ativos do que o plano permite, os mais recentes continuam ativos e os demais ficam': 'When you return to the free plan, nothing is deleted. If you have more active goals than the plan allows, the most recent stay active and the others are',
'pausados': 'paused',
'até você escolher; histórico, materiais e exportação continuam disponíveis.': 'until you choose; history, materials and export remain available.',
'Reembolso:': 'Refunds:',
'[política a definir pelo responsável]': '[policy to be defined by the controller]',
'. Até que ela seja definida, o cancelamento interrompe a renovação e não gera estorno do período em curso.': '. Until it is defined, cancellation stops renewal and does not refund the current period.',
'Acesso promocional': 'Promotional access',
'Podemos conceder acesso a um plano pago por período determinado, sem cobrança. Ao terminar, a conta volta ao plano gratuito pelas mesmas regras acima.': 'We may grant access to a paid plan for a set period, free of charge. When it ends, the account returns to the free plan under the same rules above.',
'Tudo o que você cria ou envia — objetivos, notas, matérias, tópicos, tarefas, links e arquivos PDF — continua sendo seu. Você nos concede apenas a licença necessária para armazenar, processar e exibir esse conteúdo para você, enquanto a conta existir.': 'Everything you create or upload — goals, notes, subjects, topics, tasks, links and PDF files — remains yours. You grant us only the license needed to store, process and display that content to you, for as long as the account exists.',
'Você declara ter o direito de usar os arquivos que envia. Não fiscalizamos o conteúdo dos arquivos, mas podemos removê-los mediante ordem legal ou notificação fundamentada de violação de direitos.': 'You declare that you have the right to use the files you upload. We do not inspect file contents, but we may remove them upon a legal order or a substantiated notice of rights infringement.',
'Aceitamos apenas PDF, de até 25 MB e 800 páginas por arquivo, dentro das cotas de quantidade e espaço do seu plano. Links precisam usar https.': 'We accept only PDF, up to 25 MB and 800 pages per file, within your plan’s quantity and storage quotas. Links must use https.',
'Você pode exportar seu conteúdo em JSON e CSV a qualquer momento, em qualquer plano, inclusive após cancelar a assinatura.': 'You can export your content as JSON and CSV at any time, on any plan, including after cancelling the subscription.',
'Ao usar o serviço, você se compromete a não:': 'By using the service, you agree not to:',
'tentar acessar contas, dados ou áreas que não sejam suas, nem contornar limites, cotas ou controles de segurança;': 'attempt to access accounts, data or areas that are not yours, or bypass limits, quotas or security controls;',
'usar automação para sobrecarregar o serviço ou para criar contas em massa;': 'use automation to overload the service or to create accounts in bulk;',
'enviar arquivos ou textos ilícitos, maliciosos ou que violem direitos de terceiros;': 'upload files or texts that are unlawful, malicious or infringe third-party rights;',
'revender ou sublicenciar o serviço.': 'resell or sublicense the service.',
'Em caso de violação, podemos limitar, suspender ou encerrar a conta. Sempre que possível, avisaremos antes e daremos oportunidade de exportar seus dados.': 'In case of violation, we may limit, suspend or terminate the account. Whenever possible, we will notify you first and give you the opportunity to export your data.',
'Os recursos de IA fazem parte dos planos pagos, com limite de ações por mês e por dia informado na página de planos. São opcionais, podem estar desligados no ambiente e, quando existem, só rodam por ação explícita sua: sugerir estrutura de matérias e tópicos, sugerir distribuição do plano e redigir o resumo da semana.': 'AI features are part of the plans, with the monthly and daily action limits stated on the plans page. They are optional, may be turned off in the environment and, when available, run only on your explicit action: suggesting the subject and topic structure, suggesting a plan distribution and writing the weekly summary.',
'Toda resposta é uma': 'Every answer is a',
'prévia': 'preview',
'. Nada é criado ou alterado sem a sua revisão e confirmação. A resposta pode conter erros e você é responsável por conferir antes de aplicar.': '. Nothing is created or changed without your review and confirmation. The answer may contain errors and you are responsible for checking before applying it.',
'Há limites diários por plano e um limite global. Quando esgotados, o serviço avisa e não envia nada.': 'There are daily limits per plan and a global limit. When exhausted, the service tells you and sends nothing.',
'O que é enviado ao provedor e o que guardamos está descrito na': 'What is sent to the provider and what we keep is described in the',
'Lembretes por notificação do navegador, push ou e-mail são opcionais e dependem de permissões do seu aparelho e do sistema. Fazemos o melhor para entregá-los no horário, respeitando o limite diário e o horário de silêncio que você configurar, mas': 'Reminders by browser notification, push or email are optional and depend on your device and system permissions. We do our best to deliver them on time, respecting the daily limit and the quiet hours you set, but we',
'não prometemos entrega pontual': 'do not promise timely delivery',
': sistemas operacionais e navegadores podem atrasar ou descartar notificações. Não trate o serviço como alarme.': ': operating systems and browsers may delay or discard notifications. Do not treat the service as an alarm.',
'Trabalhamos para manter o serviço no ar, mas não garantimos disponibilidade ininterrupta. O aplicativo funciona sem internet para registrar sessões e consultar o plano, e sincroniza quando a conexão voltar; entrar, pagar e importar arquivos exigem conexão.': 'We work to keep the service up, but we do not guarantee uninterrupted availability. The app works offline for logging sessions and viewing the plan, and syncs when the connection returns; signing in, paying and importing files require a connection.',
'Podemos adicionar, alterar ou remover recursos e ajustar limites do catálogo de planos. Mudanças que reduzam recursos de um plano pago valem a partir da renovação seguinte.': 'We may add, change or remove features and adjust the plan catalog limits. Changes that reduce features of a paid plan take effect from the next renewal.',
'Podemos alterar estes termos. A versão vigente é a publicada nesta página, com a data no topo; mudanças relevantes serão avisadas dentro do aplicativo antes de valer.': 'We may change these terms. The current version is the one published on this page, with the date at the top; significant changes will be announced inside the app before taking effect.',
'Por você': 'By you',
': em Preferências, a qualquer momento. A exclusão é imediata e irreversível: apaga a conta, o conteúdo de estudo e os arquivos enviados, e encerra a assinatura em curso sem estorno automático. Exporte seus dados antes, se quiser guardá-los.': ': in Preferences, at any time. Deletion is immediate and irreversible: it deletes the account, the study content and the uploaded files, and ends the current subscription without automatic refund. Export your data first if you want to keep it.',
'Por nós': 'By us',
': em caso de violação destes termos, fraude ou exigência legal, ou se o serviço for descontinuado — neste caso, com aviso prévio e prazo para exportação.': ': in case of violation of these terms, fraud or legal requirement, or if the service is discontinued — in that case, with prior notice and time to export.',
'O serviço é fornecido “como está”. Não garantimos que ele atenda a toda necessidade específica nem que esteja livre de erros.': 'The service is provided “as is”. We do not guarantee that it meets every specific need or that it is free of errors.',
'Não respondemos por resultados de estudo, provas, concursos ou avaliações, por decisões tomadas com base nos relatórios, nem por perda de dados causada por falhas do seu aparelho ou do seu navegador (por exemplo, ao limpar os dados do site antes de sincronizar).': 'We are not responsible for study, test, exam or assessment results, for decisions made based on the reports, or for data loss caused by failures of your device or browser (for example, clearing the site data before syncing).',
'Nossa responsabilidade, quando houver, limita-se ao valor pago por você pelo serviço nos doze meses anteriores ao fato, salvo quando a lei não permitir essa limitação. Nada nestes termos exclui direitos garantidos pelo Código de Defesa do Consumidor.': 'Our liability, where it exists, is limited to the amount you paid for the service in the twelve months before the event, except where the law does not allow this limitation. Nothing in these terms excludes rights guaranteed by Brazil’s Consumer Protection Code.',
'Estes termos são regidos pelas leis da República Federativa do Brasil. Fica eleito o foro de': 'These terms are governed by the laws of the Federative Republic of Brazil. The venue of',
'[comarca a definir pelo responsável]': '[judicial district to be defined by the controller]',
'para resolver conflitos, sem prejuízo do foro do seu domicílio quando você for consumidor.': 'is elected to resolve disputes, without prejudice to the venue of your domicile when you are a consumer.',
'Dúvidas sobre estes termos:': 'Questions about these terms:',
'Termos de uso do Estudatta: conta, planos e cobrança, conteúdo enviado, uso da IA, notificações, disponibilidade e cancelamento.': 'Estudatta terms of use: account, plans and billing, uploaded content, AI use, notifications, availability and cancellation.',
'termos de uso estudatta, assinatura estudatta, cancelamento estudatta': 'estudatta terms of use, estudatta subscription, cancel estudatta',
'Termos de uso — Estudatta': 'Terms of use — Estudatta',
# --- 404 ---
'Página não encontrada · Estudatta': 'Page not found · Estudatta',
'Erro 404': 'Error 404',
'Página não encontrada.': 'Page not found.',
'O endereço pode ter mudado ou nunca existiu. Nem o Tatá achou esta página. O plano continua onde você parou: escolha um caminho abaixo.': 'The address may have changed or never existed. Not even Tatá could find this page. Your plan is still where you left it: pick a path below.',
'Voltar ao início': 'Back to home',
'Abrir o app': 'Open the app',
'Este endereço não existe no Estudatta.': 'This address does not exist on Estudatta.',
'Outras páginas': 'Other pages',

'Estudatta: app de estudos com plano diário, cronômetro e o mascote Tatá': 'Estudatta: study planner app with a daily plan, timer and the mascot Tatá',
'Estudatta: o app de estudos que diz o que fazer hoje': 'Estudatta: the study app that tells you what to do today',
}
