T = {
# --- home ---
'Estudatta | App de estudos: plano diário, cronômetro e revisões': 'Estudatta | Study planner app: daily plan, timer and reviews',
'Pular para o conteúdo': 'Skip to content',
'Idiomas': 'Languages',
'Concursos': 'Exams',
'Vestibular': 'College',
'Planos': 'Plans',
'Perguntas': 'FAQ',
'Criar conta': 'Create account',
'Entrar': 'Sign in',
'Plano de estudos para hoje.': 'Your study plan for today.',
'Retome quando atrasar.': 'Catch up when you fall behind.',
'Você define meta, dias e horários. O app organiza o plano, registra as sessões e transforma o que faltou em tempo a recuperar — no seu ritmo, sem culpa.': 'You set the goal, the days and the times. The app organizes the plan, logs your sessions and turns whatever you missed into time to make up — at your own pace, without guilt.',
'Começar grátis': 'Start for free',
'Ver como funciona': 'See how it works',
'Funciona no navegador e instala como app. Sem cartão para começar.': 'Works in the browser and installs as an app. No card needed to start. The app interface is currently in Portuguese (Brazil).',
'quinta, 17 set': 'Thu, Sep 17',
'Hoje': 'Today',
'Inglês': 'English',
'meta 60 min': 'goal 60 min',
'Registrado hoje': 'Logged today',
'Falta para a meta': 'Left to goal',
'Pendência anterior': 'Carried over',
'Recuperação sugerida': 'Suggested catch-up',
'Mais 40 min hoje: 20 da meta + 20 de recuperação.': '40 more min today: 20 for the goal + 20 to catch up.',
'Começar sessão': 'Start session',
'“Eu queria estudar uma hora por dia, mas não sei quanto estudei, quanto ficou pendente e como retomar.”': '“I wanted to study an hour a day, but I don’t know how much I studied, how much is still owed or how to get back on track.”',
'É para isso que o app existe. Ele não dá aula nem mede fluência: organiza o estudo que você já faz em cursos, livros, PDFs, vídeos e exercícios — e mostra, todo dia, o compromisso, o realizado e o próximo passo.': 'That is what the app is for. It doesn’t teach and it doesn’t measure fluency: it organizes the studying you already do with courses, books, PDFs, videos and exercises — and shows you, every day, the commitment, what got done and the next step.',
'Como funciona': 'How it works',
'Defina o objetivo e o edital': 'Set the goal and the syllabus',
'Objetivo, minutos por dia, dias da semana e prazo. Matérias, tópicos, materiais e páginas ficam no mesmo lugar; o conteúdo programático pode ser importado de texto, CSV ou PDF.': 'Goal, minutes per day, days of the week and deadline. Subjects, topics, materials and pages live in one place; the syllabus can be imported from text, CSV or PDF.',
'Planeje a semana': 'Plan the week',
'Horários preferidos, metas semanais de questões e de páginas e as revisões do dia. O app sugere a próxima matéria, e você decide.': 'Preferred times, weekly goals for questions and pages, and the day’s reviews. The app suggests the next subject; you decide.',
'Registre com o cronômetro e o Tatá': 'Log it with the timer and Tatá',
'Escolha o tipo de sessão, estude com o cronômetro e anote questões feitas e acertos. Esqueceu de abrir o app? O registro manual resolve. Funciona sem internet.': 'Pick the session type, study with the timer and note questions done and correct answers. Forgot to open the app? Manual logging takes care of it. Works offline.',
'Acompanhe a evolução e as conquistas': 'Track progress and achievements',
'Tempo, taxa de acerto por matéria, simulados e edital coberto. Um dia sem registro vira tempo a recuperar, e retomar o plano também conta como conquista.': 'Time, accuracy per subject, mock exams and syllabus covered. A day with nothing logged becomes time to make up, and getting back on track counts as an achievement too.',
'Recursos': 'Features',
'Do tempo estudado ao que falta estudar': 'From time studied to what is left to study',
'Tipos de sessão': 'Session types',
'Cada sessão com o seu propósito': 'Every session with its own purpose',
'Teoria, questões, revisão, leitura, aula ou prática. Nas sessões de questões, registre quantas fez e quantas acertou: o relatório mostra a taxa de acerto por matéria.': 'Theory, questions, review, reading, class or practice. In question sessions, log how many you did and how many you got right: the report shows accuracy per subject.',
'Teoria': 'Theory',
'Questões': 'Questions',
'Revisão': 'Review',
'Leitura': 'Reading',
'Aula': 'Class',
'Prática': 'Practice',
'Revisões automáticas': 'Automatic reviews',
'Estudou o tópico? A revisão já está marcada': 'Studied the topic? The review is already scheduled',
'Depois de estudar um tópico, o app agenda revisões em 1, 7 e 30 dias. Os intervalos são configuráveis, e as revisões do dia aparecem no plano de hoje.': 'After you study a topic, the app schedules reviews at 1, 7 and 30 days. The intervals are configurable, and the day’s reviews show up in today’s plan.',
'1 dia': '1 day',
'7 dias': '7 days',
'30 dias': '30 days',
'Simulados': 'Mock exams',
'Um simulado, vários sinais': 'One mock exam, many signals',
'Registre cada simulado com os acertos por matéria e acompanhe a evolução de um para o outro. O que subiu e o que ainda pede atenção ficam lado a lado.': 'Log each mock exam with correct answers per subject and follow the progress from one to the next. What improved and what still needs attention sit side by side.',
'Edital coberto': 'Syllabus covered',
'O conteúdo programático em porcentagem': 'The syllabus as a percentage',
'A porcentagem de tópicos do conteúdo programático que você já estudou. Dá para ver, de relance, quanto do edital já passou por você.': 'The percentage of syllabus topics you have already studied. At a glance, you see how much of the program you have been through.',
'Exemplo ilustrativo': 'Illustrative example',
'Próxima matéria sugerida': 'Suggested next subject',
'Terminou uma sessão? Veja o que vem depois': 'Finished a session? See what comes next',
'O app sugere o que estudar a seguir, equilibrando o peso e a dificuldade de cada matéria com o que você estudou nos últimos 14 dias. A sugestão é um ponto de partida; a escolha é sua.': 'The app suggests what to study next, balancing each subject’s weight and difficulty with what you studied in the last 14 days. The suggestion is a starting point; the choice is yours.',
'Metas semanais': 'Weekly goals',
'Tempo por dia, questões e páginas por semana': 'Time per day, questions and pages per week',
'Além da meta diária de tempo, defina metas semanais de questões e de páginas. A semana mostra o que já foi feito e o que falta, sem transformar atraso em culpa.': 'Beyond the daily time goal, set weekly goals for questions and pages. The week shows what is done and what is left, without turning delay into guilt.',
'Seu companheiro de estudo': 'Your study companion',
'Conheça o Tatá': 'Meet Tatá',
'Um cronômetro pequeno, com um marcador de livro no lugar da cauda. Ele acompanha o estado da sua sessão e não cobra nada. Prefere estudar sem mascote? Desligue em Preferências.': 'A little stopwatch with a bookmark for a tail. He follows the state of your session and never nags. Prefer to study without a mascot? Turn him off in Preferences.',
'Foco': 'Focus',
'Com o cronômetro correndo, ele abre o livro e estuda junto.': 'With the timer running, he opens his book and studies along.',
'Pausa': 'Break',
'Sessão pausada, xícara na mão. Ele espera você voltar.': 'Session paused, cup in hand. He waits for you to come back.',
'Comemorando': 'Celebrating',
'Meta cumprida ou conquista nova: ele pula de alegria com você.': 'Goal met or new achievement: he jumps for joy with you.',
'Dormindo': 'Sleeping',
'Dia de descanso também faz parte do plano. Ele cochila e amanhã retoma com você.': 'Rest days are part of the plan too. He naps and picks it up with you tomorrow.',
'Conquistas, níveis e desafios': 'Achievements, levels and challenges',
'Cada minuto conta. Inclusive o da retomada.': 'Every minute counts. Including the comeback.',
'XP pelo que você faz': 'XP for what you do',
'Minutos estudados, meta cumprida, questões, revisões e simulados rendem XP.': 'Minutes studied, goals met, questions, reviews and mock exams earn XP.',
'Níveis com nomes': 'Levels with names',
'O XP acumulado sobe você de nível, e cada nível tem nome próprio.': 'Accumulated XP raises your level, and every level has its own name.',
'Desafios semanais': 'Weekly challenges',
'Desafios novos a cada semana, para dar um objetivo curto ao estudo.': 'New challenges every week, to give your studying a short-term target.',
'Recordes pessoais': 'Personal records',
'Suas melhores marcas ficam registradas. O único recorde a bater é o seu.': 'Your best marks are recorded. The only record to beat is your own.',
'São mais de 40 conquistas. Algumas delas:': 'There are more than 40 achievements. A few of them:',
'Primeira sessão': 'First session',
'A primeira sessão registrada, pelo cronômetro ou à mão.': 'The first session logged, by timer or by hand.',
'Sequência de 7 dias': '7-day streak',
'Sete dias seguidos com estudo registrado.': 'Seven days in a row with study logged.',
'10 horas': '10 hours',
'Dez horas de estudo somadas no app.': 'Ten hours of study added up in the app.',
'Retomada': 'Comeback',
'Você recuperou 1 hora de tempo pendente.': 'You made up 1 hour of owed time.',
'100 questões': '100 questions',
'Cem questões registradas nas suas sessões.': 'One hundred questions logged in your sessions.',
'Pontaria': 'Sharpshooter',
'80% de acerto em 100 questões.': '80% accuracy across 100 questions.',
'Metade do edital': 'Half the syllabus',
'Metade dos tópicos do conteúdo programático estudada.': 'Half of the syllabus topics studied.',
'Primeiro simulado': 'First mock exam',
'O primeiro simulado registrado, com os acertos por matéria.': 'The first mock exam logged, with correct answers per subject.',
'Você contra você mesmo': 'You against yourself',
'Não há ranking entre pessoas. A comparação é sempre com o seu próprio histórico.': 'There is no leaderboard. The comparison is always with your own history.',
'Quebrar a sequência não apaga nada': 'Breaking the streak erases nothing',
'Conquistas, XP e nível continuam com você. A sequência recomeça, e a Retomada também é uma conquista.': 'Achievements, XP and level stay with you. The streak restarts, and the Comeback is an achievement too.',
'Para quem': 'Who it is for',
'Qualquer estudo com meta de tempo': 'Any studying with a time goal',
'Edital longo. Plano do dia curto.': 'Long syllabus. Short daily plan.',
'Matérias, tópicos, PDFs com intervalo de páginas, revisões, questões e simulados. Você sabe onde parou e o que vem em seguida.': 'Subjects, topics, PDFs with page ranges, reviews, questions and mock exams. You know where you stopped and what comes next.',
'Ver para concursos →': 'See it for civil service exams →',
'Vestibular e ENEM': 'College entrance exams',
'Muitas matérias, uma semana possível.': 'Many subjects, one doable week.',
'Áreas e matérias como tópicos, metas semanais de questões e simulados para acompanhar cada área.': 'Areas and subjects as topics, weekly question goals and mock exams to track each area.',
'Ver para ENEM e vestibular →': 'See it for entrance exams →',
'Faculdade e residência': 'College and residency',
'Disciplina, prova e plantão no mesmo plano.': 'Course, exam and shift in the same plan.',
'Prazo de cada prova, revisões dos temas e pausas planejadas nas semanas mais pesadas.': 'A deadline for each exam, reviews of the topics and planned breaks in the heaviest weeks.',
'60 minutos por dia. Mesmo depois de ontem.': '60 minutes a day. Even after yesterday.',
'Aula, leitura, podcast, prática: cada tipo de sessão soma no mesmo objetivo e a constância fica visível.': 'Class, reading, podcast, practice: every session type adds to the same goal and consistency becomes visible.',
'Ver para idiomas →': 'See it for languages →',
'Rotina pessoal': 'Personal routine',
'Atrasou ontem? Hoje dá para retomar.': 'Missed yesterday? Today you can catch up.',
'Leitura, instrumento, organização da casa. Qualquer prática com meta de tempo cabe no mesmo plano.': 'Reading, an instrument, tidying the house. Any practice with a time goal fits in the same plan.',
'Tom escolhido por você': 'A tone you choose',
'Acolhedor, direto ou firme. Nenhum deles trata você como criança.': 'Warm, direct or firm. None of them treats you like a child.',
'Sem registro ≠ sem estudo': 'Not logged ≠ not studied',
'“Você estudou e esqueceu de registrar?” — a pendência se ajusta.': '“Studied and forgot to log it?” — the balance adjusts.',
'Pausa planejada': 'Planned break',
'Férias e semanas difíceis não viram dívida.': 'Holidays and hard weeks don’t become debt.',
'Relatório honesto': 'Honest report',
'Mede constância, tempo e taxa de acerto — não fluência, domínio ou aprovação.': 'It measures consistency, time and accuracy — not fluency, mastery or passing.',
'Gratuito': 'Free',
'Para sempre, sem cartão': 'Forever, no card',
'1 objetivo ativo': '1 active goal',
'Cronômetro, registro manual, saldo e recuperação': 'Timer, manual logging, balance and catch-up',
'Plano semanal e lembrete no horário planejado': 'Weekly plan and a reminder at the planned time',
'Relatório da semana': 'Weekly report',
'20 materiais (até 100 MB)': '20 materials (up to 100 MB)',
'Revisões, simulados, conquistas e o Tatá': 'Reviews, mock exams, achievements and Tatá',
'Tatá com IA: 10 conversas por mês e 20 falas com voz natural': 'Tatá with AI: 10 chats a month and 20 natural-voice lines',
'Essencial': 'Essential',
'Recomendado': 'Recommended',
'/ mês': '/ month',
'ou R$ 94,80 por ano (R$ 7,90 por mês)': 'or R$ 94.80 a year (R$ 7.90 a month)',
'Até 3 objetivos ativos': 'Up to 3 active goals',
'IA para organizar o conteúdo e conversar com o Tatá: 60 ações por mês': 'AI to organize content and chat with Tatá: 60 actions a month',
'Tatá com voz natural: 300 falas por mês': 'Tatá with natural voice: 300 lines a month',
'Lembretes completos e resumo semanal por e-mail': 'Full reminders and a weekly summary by email',
'Relatórios da semana, do mês e do trimestre': 'Weekly, monthly and quarterly reports',
'Distribuição automática das tarefas na semana': 'Automatic distribution of tasks across the week',
'100 materiais (até 1 GB)': '100 materials (up to 1 GB)',
'Começar com o Essencial': 'Start with Essential',
'Completo': 'Complete',
'ou R$ 190,80 por ano (R$ 15,90 por mês)': 'or R$ 190.80 a year (R$ 15.90 a month)',
'Objetivos ativos ilimitados': 'Unlimited active goals',
'IA para organizar o conteúdo e conversar com o Tatá: 200 ações por mês': 'AI to organize content and chat with Tatá: 200 actions a month',
'Tatá com voz natural: 1.000 falas por mês': 'Tatá with natural voice: 1,000 lines a month',
'Tudo do Essencial': 'Everything in Essential',
'Materiais ilimitados (até 5 GB)': 'Unlimited materials (up to 5 GB)',
'Começar com o Completo': 'Start with Complete',
'Preços em reais. O plano anual sai 20% mais barato que 12 mensalidades. Histórico e exportação dos seus dados nunca dependem de assinatura, e o preço não muda com o tempo que você estuda.': 'Prices in Brazilian reais (BRL). The yearly plan is 20% cheaper than 12 monthly payments. Your history and data export never depend on a subscription, and the price doesn’t change with how much you study.',
'O que o app faz — e o que não faz': 'What the app does — and what it doesn’t',
'O app ensina idiomas ou tem conteúdo de concurso?': 'Does the app teach languages or include exam content?',
'Não. Ele organiza o estudo que você faz em cursos, livros, vídeos e aulas, e acompanha o tempo dedicado a cada parte.': 'No. It organizes the studying you do with courses, books, videos and classes, and tracks the time spent on each part.',
'O que acontece quando eu não registro um dia?': 'What happens when I don’t log a day?',
'O tempo da meta entra como pendência, conforme a regra que você escolheu: distribuir nos próximos dias, acumular e decidir depois, ou só avisar. Você pode registrar depois se estudou e esqueceu.': 'The goal’s time becomes owed time, following the rule you chose: spread it over the next days, accumulate it and decide later, or just be notified. You can log it later if you studied and forgot.',
'Funciona sem internet?': 'Does it work offline?',
'Sim. Sessões ficam salvas no aparelho e sincronizam quando você voltar à internet. Login, pagamento e importação de arquivos precisam de conexão.': 'Yes. Sessions are saved on the device and sync when you are back online. Signing in, paying and importing files need a connection.',
'Preciso instalar algo?': 'Do I need to install anything?',
'Não. Abre no navegador e pode ser adicionado à tela inicial do celular ou do computador como um app.': 'No. It opens in the browser and can be added to your phone’s or computer’s home screen as an app.',
'Se eu quebrar a sequência, perco conquistas?': 'If I break my streak, do I lose achievements?',
'Não. Conquistas, XP e nível ficam com você. Só a contagem da sequência recomeça, e não há ranking com outras pessoas: a comparação é com você mesmo.': 'No. Achievements, XP and level stay with you. Only the streak count restarts, and there is no leaderboard: the comparison is with yourself.',
'Dá para desligar o Tatá?': 'Can I turn Tatá off?',
'Sim. Em Preferências, dentro do app, você esconde o mascote quando quiser.': 'Yes. In Preferences, inside the app, you can hide the mascot whenever you like.',
'O relatório diz se estou aprendendo?': 'Does the report tell me whether I am learning?',
'Não. Ele mostra constância, tempo e taxa de acerto nas questões que você registra. Aprendizado se mede nos seus próprios exercícios, provas e conversas.': 'No. It shows consistency, time and accuracy on the questions you log. Learning is measured in your own exercises, exams and conversations.',
'Comece hoje, sem cartão': 'Start today, no card required',
'Crie sua conta gratuita e defina o primeiro objetivo em dois minutos. Prefere só receber novidades? Deixe seu e-mail. Sem spam, sem cobrança.': 'Create your free account and set your first goal in two minutes. Would rather just hear about updates? Leave your email. No spam, no charges.',
'Criar conta grátis': 'Create a free account',
'E-mail': 'Email',
'Receber novidades': 'Get updates',
'Privacidade': 'Privacy',
'Termos': 'Terms',
'Contato': 'Contact',
'Cookies': 'Cookies',
'App de estudos grátis: plano diário com meta de minutos, cronômetro, revisões espaçadas, questões e simulados. Atrasou? O tempo pendente vira recuperação.': 'Free study planner app: a daily plan with a minutes goal, timer, spaced reviews, questions and mock exams. Fell behind? Owed time turns into catch-up.',
'app de estudos, app para organizar estudos, planner de estudos, plano de estudos, cronograma de estudos, cronômetro de estudos, controle de horas de estudo, revisão espaçada, aplicativo de estudos gratuito': 'study planner app, study tracker, study schedule app, study timer, track study hours, spaced repetition planner, free study app, study habit tracker',
'Site': 'Site',
'Demonstração da tela Hoje: meta de 60 minutos, 40 registrados, 60 de pendência anterior e 20 de recuperação sugerida': 'Demo of the Today screen: 60-minute goal, 40 logged, 60 carried over and 20 suggested catch-up',
'O problema': 'The problem',
'equivale a R$ 7,90 por mês': 'equivalent to R$ 7.90 a month',
'equivale a R$ 15,90 por mês': 'equivalent to R$ 15.90 a month',
'voce@exemplo.com': 'you@example.com',
'Rodapé': 'Footer',
'R$ 9,90': 'R$ 9.90',
'R$ 19,90': 'R$ 19.90',
'R$ 94,80': 'R$ 94.80',
'R$ 190,80': 'R$ 190.80',
# --- idiomas ---
'App para estudar inglês e outros idiomas todo dia | Estudatta': 'Language study planner: study English or any language every day | Estudatta',
'Estude idiomas 60 minutos por dia.': 'Study a language 60 minutes a day.',
'Mesmo depois de ontem.': 'Even after yesterday.',
'Inglês, espanhol, francês, japonês, Libras ou qualquer um de mais de 90 idiomas. Curso, podcast, série ou livro: o app acompanha o tempo dedicado a cada frente e mantém a constância visível. Ele não ensina o idioma — organiza o estudo que você já faz e mostra como retomar quando um dia fica para trás.': 'English, Spanish, French, Japanese, sign language or any of more than 90 languages. Course, podcast, TV series or book: the app tracks the time spent on each front and keeps your consistency visible. It doesn’t teach the language — it organizes the studying you already do and shows you how to catch up when a day slips.',
'Ver o saldo do dia': 'See the daily balance',
'Uma meta, várias frentes': 'One goal, several fronts',
'Tudo o que você já faz no idioma cabe no mesmo plano': 'Everything you already do in the language fits in the same plan',
'Curso ou aula': 'Course or class',
'A aula conta na meta': 'Class time counts toward the goal',
'Presencial, on-line ou particular: abra o cronômetro durante a aula ou registre depois. O tempo entra no objetivo do dia.': 'In person, online or private: start the timer during class or log it afterwards. The time goes into the day’s goal.',
'Podcast e série': 'Podcasts and series',
'Listening no trajeto': 'Listening on the commute',
'Ouviu vinte minutos no ônibus? Registre em segundos, ainda hoje ou amanhã. Sem internet também funciona.': 'Listened for twenty minutes on the bus? Log it in seconds, today or tomorrow. Works offline too.',
'Livro e leitura': 'Books and reading',
'Páginas como material': 'Pages as material',
'Cadastre o livro ou o PDF e o intervalo de páginas. Você sabe onde parou e quanto falta.': 'Add the book or PDF and the page range. You know where you stopped and how much is left.',
'Vocabulário e exercícios': 'Vocabulary and exercises',
'Uma frente para cada coisa': 'One front for each thing',
'Listening, vocabulário, gramática, conversação: cada frente vira um tópico do mesmo objetivo, com o tempo somado no relatório.': 'Listening, vocabulary, grammar, speaking: each front becomes a topic in the same goal, with time added up in the report.',
'Mais de 90 idiomas': 'More than 90 languages',
'Inglês já vem escolhido. Troque pelo idioma que quiser.': 'English is preselected. Switch to any language you like.',
'Ao criar o objetivo, escolha o idioma na lista: os mais procurados aparecem primeiro, e o nome do objetivo acompanha a escolha.': 'When creating the goal, pick the language from the list: the most popular come first, and the goal’s name follows your choice.',
'Espanhol': 'Spanish', 'Francês': 'French', 'Alemão': 'German', 'Italiano': 'Italian', 'Japonês': 'Japanese', 'Chinês (mandarim)': 'Chinese (Mandarin)', 'Coreano': 'Korean', 'Russo': 'Russian', 'Árabe': 'Arabic', 'Libras': 'Libras (Brazilian Sign Language)', 'Hebraico': 'Hebrew', 'Holandês': 'Dutch', 'Sueco': 'Swedish', 'Turco': 'Turkish', 'Grego': 'Greek', 'Hindi': 'Hindi', 'Guarani': 'Guarani', 'Latim': 'Latin', 'Esperanto': 'Esperanto',
'e muitos outros': 'and many more',
'Sessões, metas e conquistas': 'Sessions, goals and achievements',
'Leitura, aula e prática, cada uma no seu lugar': 'Reading, class and practice, each in its place',
'Diga o que foi a sessão': 'Say what the session was',
'Aula, leitura, prática, revisão, teoria ou questões. O relatório separa o tempo por tipo, e nas sessões de exercícios você anota quantas questões fez e acertou.': 'Class, reading, practice, review, theory or questions. The report splits time by type, and in exercise sessions you note how many questions you did and got right.',
'Páginas por semana, minutos por dia': 'Pages per week, minutes per day',
'Além da meta diária de tempo, defina quantas páginas quer ler na semana, no livro ou no PDF. Também dá para ter uma meta semanal de questões.': 'Beyond the daily time goal, set how many pages you want to read this week, in the book or PDF. You can also have a weekly question goal.',
'A constância vira XP': 'Consistency becomes XP',
'Minutos estudados, metas cumpridas e revisões rendem XP, sobem de nível e liberam conquistas. Não há ranking com outras pessoas, e quebrar a sequência não tira nada do que você já conquistou.': 'Minutes studied, goals met and reviews earn XP, raise your level and unlock achievements. There is no leaderboard, and breaking a streak takes nothing away from what you have already earned.',
'Ver as conquistas →': 'See the achievements →',
'Saldo e recuperação': 'Balance and catch-up',
'De onde sai “mais 40 min hoje”': 'Where “40 more min today” comes from',
'Meta de hoje': 'Today’s goal',
'O compromisso que você definiu para este objetivo, nos dias que escolheu.': 'The commitment you set for this goal, on the days you chose.',
'Duas sessões pelo cronômetro ou um registro manual. Faltam 20 min para a meta.': 'Two timer sessions or one manual entry. 20 min left to the goal.',
'Ontem não teve registro. A meta do dia virou tempo a recuperar — sem juros, sem culpa.': 'Nothing was logged yesterday. The day’s goal became time to make up — no interest, no guilt.',
'Com a regra “distribuir em 3 dias”, a pendência entra aos poucos: 20 min hoje, 20 amanhã, 20 depois.': 'With the “spread over 3 days” rule, the owed time comes in gradually: 20 min today, 20 tomorrow, 20 the day after.',
'Resultado:': 'Result:',
'mais 40 min hoje — 20 da meta + 20 de recuperação': '40 more min today — 20 for the goal + 20 to catch up',
'. Prefere recuperar tudo de uma vez, ou só ser avisado? A regra é sua. Estudou e esqueceu de registrar? Registre depois: a pendência se ajusta.': '. Would rather make it all up at once, or just be notified? The rule is yours. Studied and forgot to log it? Log it later: the balance adjusts.',
'Registrado': 'Logged',
'Falta da meta': 'Left to goal',
'Recuperação': 'Catch-up',
'Defina o compromisso': 'Set the commitment',
'Objetivo, minutos por dia, dias da semana, data de início e horários preferidos. Matérias, tópicos, materiais e páginas ficam organizados no mesmo lugar.': 'Goal, minutes per day, days of the week, start date and preferred times. Subjects, topics, materials and pages stay organized in one place.',
'Registre a sessão': 'Log the session',
'Cronômetro para quem estuda com o app aberto; registro manual rápido para quem estudou e lembrou depois. Funciona sem internet e sincroniza quando voltar.': 'A timer for those who study with the app open; quick manual logging for those who studied and remembered later. Works offline and syncs when you are back.',
'Retome quando atrasar': 'Catch up when you fall behind',
'Um dia sem registro vira tempo a recuperar, pela regra que você escolheu. Recupere tudo hoje ou distribua nos próximos dias — o plano compara antes e depois.': 'A day with nothing logged becomes time to make up, by the rule you chose. Make it all up today or spread it over the next days — the plan compares before and after.',
'Constância, não fluência': 'Consistency, not fluency',
'O relatório mostra dias com registro e tempo por frente. Ele não avalia pronúncia, vocabulário ou nível.': 'The report shows days with logs and time per front. It doesn’t assess pronunciation, vocabulary or level.',
'Acolhedor, direto ou firme. A mensagem do dia muda; a cobrança não vira culpa.': 'Warm, direct or firm. The daily message changes; the nudge never turns into guilt.',
'Dia sem registro ≠ dia perdido': 'Unlogged day ≠ lost day',
'Esqueceu de registrar? Registre depois. Não estudou? Vira tempo a recuperar, pela regra que você escolheu.': 'Forgot to log it? Log it later. Didn’t study? It becomes time to make up, by the rule you chose.',
'Viagem, prova na faculdade, semana pesada no trabalho: marque a pausa e a pendência não cresce.': 'A trip, a college exam, a heavy week at work: mark the break and owed time doesn’t grow.',
'Perguntas de quem estuda idiomas': 'Questions from language learners',
'Quais idiomas posso acompanhar?': 'Which languages can I track?',
'Mais de 90. O inglês já vem escolhido ao criar o objetivo, e você troca por espanhol, francês, alemão, italiano, japonês, chinês, coreano, Libras, ASL e muitos outros. Se o seu não estiver na lista, escolha “Outro idioma” e dê o nome que quiser.': 'More than 90. English is preselected when you create the goal, and you can switch to Spanish, French, German, Italian, Japanese, Chinese, Korean, Libras, ASL and many more. If yours isn’t listed, pick “Other language” and name it whatever you like.',
'Dá para estudar dois idiomas ao mesmo tempo?': 'Can I study two languages at the same time?',
'Sim. Cada idioma é um objetivo, com meta, dias e saldo próprios. No Gratuito fica 1 objetivo ativo; no Essencial, até 3; no Completo, sem limite.': 'Yes. Each language is a goal, with its own target, days and balance. Free has 1 active goal; Essential, up to 3; Complete, no limit.',
'O app ensina o idioma?': 'Does the app teach the language?',
'Não. Ele não tem aulas, exercícios nem correção. Organiza o estudo que você já faz — curso, podcast, série, livro — e acompanha o tempo dedicado a cada frente.': 'No. It has no lessons, exercises or grading. It organizes the studying you already do — course, podcast, series, book — and tracks the time spent on each front.',
'Funciona com qualquer curso ou método?': 'Does it work with any course or method?',
'Sim. Curso presencial ou on-line, aula particular, aplicativo de idiomas, livro didático, intercâmbio: o objetivo é seu, o material é seu. O app registra o tempo e mantém o plano.': 'Yes. In-person or online course, private lessons, a language app, a textbook, an exchange program: the goal is yours, the material is yours. The app logs the time and keeps the plan.',
'Consigo separar o tempo por frente — listening, vocabulário, gramática, conversação?': 'Can I split time by front — listening, vocabulary, grammar, speaking?',
'Sim. Cada frente é um tópico dentro do objetivo. Ao registrar uma sessão, você escolhe o tópico; o relatório mostra quanto tempo foi para cada um.': 'Yes. Each front is a topic inside the goal. When logging a session, you pick the topic; the report shows how much time went to each.',
'Ouvir podcast no trajeto conta?': 'Does listening to a podcast on the commute count?',
'Conta, se você quiser que conte. Registre manualmente a duração e o tópico quando lembrar; a pendência do dia se ajusta.': 'It does, if you want it to. Manually log the duration and topic when you remember; the day’s balance adjusts.',
'E se 60 minutos por dia não couber na minha semana?': 'What if 60 minutes a day doesn’t fit my week?',
'Defina a meta que cabe — 20, 30, 45 minutos — e os dias da semana. Semanas difíceis e férias entram como pausa planejada, sem virar dívida.': 'Set the goal that fits — 20, 30, 45 minutes — and the days of the week. Hard weeks and holidays go in as planned breaks, without becoming debt.',
'O relatório mede fluência?': 'Does the report measure fluency?',
'Não. Ele mede constância e tempo por objetivo e por frente. Fluência se mede nas suas conversas, provas e no que você entende do que ouve e lê.': 'No. It measures consistency and time per goal and per front. Fluency shows in your conversations, tests and in what you understand of what you hear and read.',
'Organize o estudo de inglês, espanhol, japonês ou mais de 90 idiomas: meta diária, aulas, podcasts e leitura no mesmo plano, com revisões e conquistas.': 'Organize your study of English, Spanish, Japanese or 90+ languages: a daily goal, classes, podcasts and reading in one plan, with reviews and achievements.',
'app para estudar inglês, app para estudar idiomas, plano de estudos de inglês, estudar inglês todo dia, rotina de estudo de inglês, app de estudo de espanhol, app de estudo de japonês, controle de tempo de estudo de idiomas': 'language study planner, language learning tracker, study English every day, language study routine, track language study time, Spanish study app, Japanese study planner',
'App para estudar inglês e outros idiomas todo dia': 'Language study planner: study English or any language every day',
'Exemplo do cartão de Inglês: 40 de 60 minutos registrados, 20 minutos de recuperação sugerida': 'Example of the English card: 40 of 60 minutes logged, 20 minutes of suggested catch-up',
'Sem promessas': 'No promises',
}
