T = {
# --- concursos ---
'Plano de estudos para concurso: edital e revisões | Estudatta': 'Study plan for civil service exams: syllabus and reviews | Estudatta',
'Plano de estudos para concurso.': 'A study plan for civil service exams.',
'Edital longo, dia curto.': 'Long syllabus, short day.',
'Matérias, tópicos, PDFs com intervalo de páginas e tarefas em um só lugar. Todo dia você vê o compromisso, o que já registrou e o próximo passo. O app não tem aulas nem banco de questões: organiza o estudo que você já faz, com revisões, questões e simulados registrados.': 'Subjects, topics, PDFs with page ranges and tasks in one place. Every day you see the commitment, what you have logged and the next step. The app has no lessons or question bank: it organizes the studying you already do, with reviews, questions and mock exams logged.',
'Ver a importação do edital': 'See the syllabus import',
'Árvore de matérias e tópicos': 'Subject and topic tree',
'Concurso · Analista': 'Exam · Analyst',
'4 matérias': '4 subjects',
'Direito Constitucional': 'Constitutional Law',
'5 tópicos': '5 topics',
'Direitos fundamentais': 'Fundamental rights',
'PDF · p. 12–34': 'PDF · pp. 12–34',
'Controle de constitucionalidade': 'Judicial review',
'Vídeo · 18 min': 'Video · 18 min',
'Organização dos Poderes': 'Separation of powers',
'PDF · p. 35–61': 'PDF · pp. 35–61',
'Direito Administrativo': 'Administrative Law',
'6 tópicos': '6 topics',
'Língua Portuguesa': 'Portuguese',
'4 tópicos': '4 topics',
'Raciocínio lógico': 'Logical reasoning',
'3 tópicos': '3 topics',
'Exemplo ilustrativo. As matérias e os tópicos são os do seu edital.': 'Illustrative example. The subjects and topics are the ones in your syllabus.',
'Do edital ao dia': 'From the syllabus to the day',
'O conteúdo programático inteiro, sem perder o fio': 'The whole syllabus, without losing the thread',
'Matérias e tópicos': 'Subjects and topics',
'O edital vira uma árvore': 'The syllabus becomes a tree',
'Cada matéria com seus tópicos, na ordem que você preferir. Ao registrar uma sessão, você escolhe o tópico; o relatório soma o tempo por matéria.': 'Each subject with its topics, in the order you prefer. When logging a session, you pick the topic; the report adds up time per subject.',
'PDFs e materiais': 'PDFs and materials',
'Intervalo de páginas por tópico': 'Page range per topic',
'Envie o PDF, cadastre o livro físico ou cole o link da videoaula. Ligue o material ao tópico com o intervalo — “p. 12–34” — e saiba onde parou.': 'Upload the PDF, add the physical book or paste the video lesson link. Attach the material to the topic with the range — “pp. 12–34” — and know where you stopped.',
'Tarefas': 'Tasks',
'O que fazer além do tempo': 'What to do beyond time',
'Revisar a unidade, resolver a lista, refazer as questões erradas: tarefas ficam junto do tópico e aparecem no plano do dia.': 'Review the unit, work through the exercise list, redo the questions you got wrong: tasks sit with the topic and show up in the daily plan.',
'Prazo da prova': 'Exam date',
'Um fim à vista': 'An end in sight',
'Informe a data da prova como prazo final do objetivo. Saiu o edital ou mudou a data? Ajuste o prazo; o histórico fica como está.': 'Set the exam date as the goal’s deadline. New notice out or date changed? Adjust the deadline; the history stays as it is.',
'Revisões, questões e simulados': 'Reviews, questions and mock exams',
'Além do tempo: o que você revisou, acertou e cobriu': 'Beyond time: what you reviewed, got right and covered',
'1, 7 e 30 dias depois': '1, 7 and 30 days later',
'Ao estudar um tópico, o app agenda as revisões. Os intervalos são configuráveis, e as revisões do dia entram no plano de hoje.': 'When you study a topic, the app schedules the reviews. The intervals are configurable, and the day’s reviews go into today’s plan.',
'Taxa de acerto por matéria': 'Accuracy per subject',
'Nas sessões de questões, registre quantas fez e quantas acertou. O relatório mostra a taxa de acerto de cada matéria, e a meta semanal de questões acompanha o ritmo.': 'In question sessions, log how many you did and how many you got right. The report shows accuracy for each subject, and the weekly question goal keeps pace.',
'A evolução de um simulado para o outro': 'Progress from one mock exam to the next',
'Registre cada simulado com os acertos por matéria e veja onde você avançou e onde vale reforçar.': 'Log each mock exam with correct answers per subject and see where you improved and where it is worth reinforcing.',
'Quanto do conteúdo programático já foi estudado': 'How much of the syllabus has been studied',
'A porcentagem de tópicos do edital que já passaram por uma sessão sua.': 'The percentage of syllabus topics that have had a session of yours.',
'Peso, dificuldade e os últimos 14 dias': 'Weight, difficulty and the last 14 days',
'O app sugere o que estudar a seguir, equilibrando o peso e a dificuldade de cada matéria com o que você estudou nas últimas duas semanas. A decisão continua sua.': 'The app suggests what to study next, balancing each subject’s weight and difficulty with what you studied in the last two weeks. The decision is still yours.',
'Importação do conteúdo programático': 'Syllabus import',
'Texto, CSV ou PDF — sempre com revisão sua': 'Text, CSV or PDF — always with your review',
'Cole, envie a planilha ou o PDF': 'Paste, upload the spreadsheet or the PDF',
'Texto colado do edital, arquivo CSV (há um modelo para baixar) ou o PDF do próprio edital.': 'Text pasted from the notice, a CSV file (there is a template to download) or the notice’s own PDF.',
'Revise a prévia': 'Review the preview',
'O app monta uma proposta de matérias e tópicos. Você renomeia, move, junta ou apaga o que não fizer sentido.': 'The app drafts a proposal of subjects and topics. You rename, move, merge or delete whatever doesn’t make sense.',
'Confirme': 'Confirm',
'Nada entra no seu plano antes da sua confirmação. Se desistir, é só cancelar a importação.': 'Nothing enters your plan before you confirm. Changed your mind? Just cancel the import.',
'PDF escaneado, sem texto selecionável, não é lido: a importação avisa e você segue pelo texto colado ou pelo CSV. Nos planos Essencial e Completo, a IA pode sugerir a estrutura das matérias a partir do edital; ela só roda quando você pede e a sugestão também passa pela sua revisão.': 'A scanned PDF with no selectable text is not read: the import warns you and you continue with pasted text or CSV. On the Essential and Complete plans, AI can suggest the subject structure from the notice; it only runs when you ask, and the suggestion also goes through your review.',
'Concurso': 'Exam',
'Números, não aprovação': 'Numbers, not approval',
'O relatório mostra constância, tempo e taxa de acerto por matéria. Ele não mede domínio do conteúdo nem prevê resultado de prova.': 'The report shows consistency, time and accuracy per subject. It doesn’t measure mastery or predict exam results.',
'Estudou e esqueceu de registrar? Registre depois. Não estudou? Vira tempo a recuperar, pela regra que você escolheu.': 'Studied and forgot to log it? Log it later. Didn’t study? It becomes time to make up, by the rule you chose.',
'Semana de plantão, viagem, descanso depois de uma prova: marque a pausa e a pendência não cresce.': 'A week on call, a trip, rest after an exam: mark the break and owed time doesn’t grow.',
'Funciona sem internet': 'Works offline',
'Biblioteca, ônibus, sala de estudo sem sinal: a sessão fica salva no aparelho e sincroniza depois.': 'Library, bus, study room with no signal: the session is saved on the device and syncs later.',
'Perguntas de quem estuda para concurso': 'Questions from exam candidates',
'O app tem conteúdo, aulas ou questões de concurso?': 'Does the app have exam content, lessons or questions?',
'Não. Ele não tem videoaulas, apostilas nem banco de questões. Organiza o estudo que você faz com o seu curso, seus PDFs e seus livros, e acompanha o tempo dedicado a cada matéria. As questões que você resolve em outro lugar podem ser registradas na sessão, com os acertos.': 'No. It has no video lessons, handouts or question bank. It organizes the studying you do with your course, your PDFs and your books, and tracks the time spent on each subject. Questions you solve elsewhere can be logged in the session, with the correct answers.',
'Como funcionam as revisões automáticas?': 'How do automatic reviews work?',
'Depois de uma sessão em um tópico, o app agenda revisões em 1, 7 e 30 dias. Você pode mudar esses intervalos, e as revisões do dia aparecem no plano de hoje.': 'After a session on a topic, the app schedules reviews at 1, 7 and 30 days. You can change these intervals, and the day’s reviews show up in today’s plan.',
'Posso registrar simulados de outras plataformas?': 'Can I log mock exams from other platforms?',
'Sim. Informe o simulado e os acertos por matéria; o app guarda o histórico e mostra a evolução.': 'Yes. Enter the mock exam and the correct answers per subject; the app keeps the history and shows the progress.',
'O app aumenta minha chance de aprovação?': 'Does the app improve my chances of passing?',
'Não prometemos isso. O app mostra compromisso, tempo realizado e pendência por matéria. Aprovação depende de muita coisa que ele não mede nem controla.': 'We don’t promise that. The app shows commitment, time done and owed time per subject. Passing depends on many things it neither measures nor controls.',
'Como funciona a importação do conteúdo programático?': 'How does the syllabus import work?',
'Você cola o texto do edital, envia um CSV ou o PDF. O app propõe uma estrutura de matérias e tópicos e você revisa antes de confirmar. Texto e CSV ficam prontos na hora; o PDF é processado em seguida e avisa quando a prévia está disponível.': 'You paste the notice text, upload a CSV or the PDF. The app proposes a structure of subjects and topics and you review it before confirming. Text and CSV are ready instantly; the PDF is processed next and notifies you when the preview is available.',
'E se o PDF do edital for escaneado, sem texto selecionável?': 'What if the notice PDF is scanned, with no selectable text?',
'A importação falha com um aviso claro, em vez de inventar uma estrutura. Nesse caso, cole o texto manualmente ou use o modelo de CSV.': 'The import fails with a clear warning instead of making up a structure. In that case, paste the text manually or use the CSV template.',
'Posso estudar várias matérias no mesmo dia?': 'Can I study several subjects on the same day?',
'Sim. A meta de tempo é do objetivo; cada sessão é registrada em um tópico. No fim do dia você vê o total e a divisão por matéria.': 'Yes. The time goal belongs to the objective; each session is logged under a topic. At the end of the day you see the total and the split per subject.',
'O que acontece com o plano se a prova for adiada ou o edital mudar?': 'What happens to the plan if the exam is postponed or the syllabus changes?',
'Você altera o prazo final e edita a árvore de matérias. As sessões já registradas continuam no histórico e nos relatórios.': 'You change the deadline and edit the subject tree. Sessions already logged stay in the history and reports.',
'Consigo acompanhar mais de um concurso ao mesmo tempo?': 'Can I track more than one exam at a time?',
'Cada concurso é um objetivo. O plano Gratuito tem um objetivo ativo, o Essencial até três e o Completo não tem limite. Os detalhes estão na página de planos.': 'Each exam is a goal. The Free plan has one active goal, Essential up to three and Complete has no limit. Details are on the plans page.',
'Monte seu plano de estudos para concurso: importe o edital, organize matérias e tópicos, revise no prazo certo e registre questões e simulados. Comece grátis.': 'Build your study plan for a civil service exam: import the syllabus, organize subjects and topics, review on time and log questions and mock exams. Start for free.',
'plano de estudos para concurso, app de estudos para concurso, cronograma de estudos para concurso, organizar edital, ciclo de estudos concurso, revisão espaçada concurso, controle de questões e simulados, edital verticalizado': 'exam study planner, civil service exam study plan, syllabus tracker, exam preparation schedule, spaced review for exams, question and mock exam tracker',
'Plano de estudos para concurso: edital longo, plano do dia curto': 'Study plan for civil service exams: long syllabus, short daily plan',
'Exemplo ilustrativo de árvore de matérias: objetivo, matérias, tópicos e materiais com intervalo de páginas': 'Illustrative example of a subject tree: goal, subjects, topics and materials with page ranges',
'Exemplo do cartão de Concurso: 40 de 60 minutos registrados, 20 minutos de recuperação sugerida': 'Example of the Exam card: 40 of 60 minutes logged, 20 minutes of suggested catch-up',
# --- vestibular ---
'Cronograma de estudos para ENEM e vestibular | Estudatta': 'Study schedule for college entrance exams (ENEM) | Estudatta',
'Cronograma de estudos para o ENEM.': 'A study schedule for entrance exams.',
'Uma semana possível.': 'One doable week.',
'Áreas e matérias como tópicos, meta de minutos por dia, revisões automáticas e simulados por área. Todo dia você vê o compromisso, o que já registrou e o próximo passo. O app não tem aulas nem banco de questões: organiza o estudo que você já faz no cursinho, nos livros e nas videoaulas.': 'Areas and subjects as topics, a minutes-per-day goal, automatic reviews and mock exams per area. Every day you see the commitment, what you have logged and the next step. The app has no lessons or question bank: it organizes the studying you already do at prep school, in books and in video lessons.',
'Áreas e matérias do ENEM': 'ENEM areas and subjects',
'ENEM 2026': 'ENEM 2026',
'5 áreas': '5 areas',
'Matemática': 'Mathematics',
'12 tópicos': '12 topics',
'Funções': 'Functions',
'Vídeo · 24 min': 'Video · 24 min',
'Geometria plana': 'Plane geometry',
'PDF · p. 40–58': 'PDF · pp. 40–58',
'Ciências da Natureza': 'Natural Sciences',
'18 tópicos': '18 topics',
'Ciências Humanas': 'Humanities',
'15 tópicos': '15 topics',
'Linguagens': 'Languages',
'10 tópicos': '10 topics',
'Redação': 'Essay',
'Exemplo ilustrativo. As áreas e os tópicos são os do seu plano.': 'Illustrative example. The areas and topics are the ones in your plan.',
'Do conteúdo ao dia': 'From the content to the day',
'Todas as áreas do ENEM em um cronograma que cabe na semana': 'Every exam area in a schedule that fits the week',
'Áreas e matérias': 'Areas and subjects',
'O conteúdo vira uma árvore': 'The content becomes a tree',
'Linguagens, Humanas, Natureza, Matemática e Redação como matérias; os assuntos como tópicos. Ao registrar uma sessão, você escolhe o tópico e o relatório soma o tempo por área.': 'Languages, Humanities, Natural Sciences, Mathematics and Essay as subjects; the themes as topics. When logging a session, you pick the topic and the report adds up time per area.',
'Meta diária': 'Daily goal',
'Minutos por dia, nos dias que você tem': 'Minutes per day, on the days you have',
'Escola de manhã, cursinho à tarde? Defina os dias e os minutos possíveis. A meta é sua, e o app só cobra o que você combinou.': 'School in the morning, prep course in the afternoon? Set the days and minutes that are possible. The goal is yours, and the app only asks for what you agreed to.',
'Materiais': 'Materials',
'Livro, PDF e videoaula no tópico': 'Book, PDF and video lesson on the topic',
'Envie o PDF, cadastre o livro ou cole o link da videoaula e ligue ao tópico com o intervalo de páginas. Você sabe onde parou.': 'Upload the PDF, add the book or paste the video lesson link and attach it to the topic with the page range. You know where you stopped.',
'Data da prova': 'Exam date',
'Informe a data do ENEM ou do vestibular como prazo do objetivo. Mudou a data ou entrou outro vestibular? Ajuste o prazo; o histórico fica como está.': 'Set the ENEM or entrance exam date as the goal’s deadline. Date changed or another exam added? Adjust the deadline; the history stays as it is.',
'Taxa de acerto por área': 'Accuracy per area',
'Nas sessões de questões, registre quantas fez e quantas acertou. O relatório mostra a taxa de acerto por área e matéria, e a meta semanal de questões acompanha o ritmo.': 'In question sessions, log how many you did and how many you got right. The report shows accuracy per area and subject, and the weekly question goal keeps pace.',
'Registre cada simulado com os acertos por área e veja onde você avançou e onde vale reforçar antes da prova.': 'Log each mock exam with correct answers per area and see where you improved and where it is worth reinforcing before the exam.',
'Conteúdo coberto': 'Content covered',
'Quanto do programa já foi estudado': 'How much of the program has been studied',
'A porcentagem de tópicos que já passaram por uma sessão sua, área por área.': 'The percentage of topics that have had a session of yours, area by area.',
'Rotina real': 'Real routine',
'Escola, cursinho e prova de fim de bimestre no mesmo plano': 'School, prep course and end-of-term tests in the same plan',
'Semana de provas na escola ou viagem em família: marque a pausa e nada vira dívida.': 'Test week at school or a family trip: mark the break and nothing becomes debt.',
'Registrou depois? Vale': 'Logged it later? It counts',
'Estudou no ônibus, na biblioteca ou sem internet? Registre depois. Sessões salvas no aparelho sincronizam quando voltar.': 'Studied on the bus, at the library or offline? Log it later. Sessions saved on the device sync when you are back.',
'Tarefas do dia': 'Tasks of the day',
'Redação da semana, lista de exercícios, refazer as questões erradas do simulado: tarefas ficam junto do tópico e aparecem no plano de hoje.': 'The week’s essay, the exercise list, redoing the mock exam questions you got wrong: tasks sit with the topic and show up in today’s plan.',
'Sem ranking': 'No leaderboard',
'Conquistas e níveis comparam você com o seu histórico, não com a turma.': 'Achievements and levels compare you with your own history, not with your class.',
'ENEM': 'ENEM',
'Perguntas de quem estuda para o ENEM e vestibulares': 'Questions from students preparing for entrance exams',
'O app tem videoaulas, apostilas ou questões do ENEM?': 'Does the app have video lessons, handouts or exam questions?',
'Não. Ele organiza o estudo que você já faz com o cursinho, os livros, os PDFs e as videoaulas que escolher, e acompanha o tempo por área e matéria. As questões e os simulados feitos em outro lugar são registrados aqui, com os acertos.': 'No. It organizes the studying you already do with your prep course, books, PDFs and the video lessons you choose, and tracks time per area and subject. Questions and mock exams done elsewhere are logged here, with the correct answers.',
'Como monto o cronograma de estudos para o ENEM?': 'How do I build a study schedule for the exam?',
'Crie o objetivo com a data da prova, os minutos por dia e os dias da semana. Cadastre as áreas (Linguagens, Humanas, Natureza, Matemática e Redação) como matérias e os assuntos como tópicos. Todo dia o app mostra a meta, o que já foi registrado e o próximo passo.': 'Create the goal with the exam date, the minutes per day and the days of the week. Add the areas (Languages, Humanities, Natural Sciences, Mathematics and Essay) as subjects and the themes as topics. Every day the app shows the goal, what has been logged and the next step.',
'Dá para estudar várias matérias no mesmo dia?': 'Can I study several subjects on the same day?',
'Sim. A meta de tempo é do objetivo; cada sessão é registrada em um tópico. No fim do dia você vê o total e a divisão por área.': 'Yes. The time goal belongs to the objective; each session is logged under a topic. At the end of the day you see the total and the split per area.',
'Como acompanho os simulados por área?': 'How do I track mock exams per area?',
'Registre cada simulado com os acertos por área ou matéria. O histórico mostra a evolução de um simulado para o outro e onde vale reforçar.': 'Log each mock exam with correct answers per area or subject. The history shows the progress from one mock exam to the next and where it is worth reinforcing.',
'E a redação?': 'What about the essay?',
'Cadastre Redação como matéria e registre as sessões de escrita e correção. Se quiser, use tarefas para “escrever um texto por semana”: elas aparecem no plano do dia.': 'Add Essay as a subject and log writing and correction sessions. If you like, use tasks for “write one essay a week”: they show up in the daily plan.',
'Perdi uma semana. E agora?': 'I lost a week. Now what?',
'O tempo que faltou vira pendência, pela regra que você escolheu: distribuir nos próximos dias, acumular e decidir depois, ou só avisar. Nas semanas de prova da escola, use a pausa planejada para não gerar dívida.': 'The missing time becomes owed time, by the rule you chose: spread it over the next days, accumulate it and decide later, or just be notified. In school test weeks, use a planned break so no debt builds up.',
'O app aumenta minha nota?': 'Does the app raise my score?',
'Não prometemos isso. O app mostra constância, tempo por área, taxa de acerto e evolução nos simulados. A nota depende de muita coisa que ele não mede.': 'We don’t promise that. The app shows consistency, time per area, accuracy and progress in mock exams. Your score depends on many things it doesn’t measure.',
'Serve para vestibulares como Fuvest, Unicamp e UFRGS?': 'Does it work for entrance exams like Fuvest, Unicamp and UFRGS?',
'Sim. Cada vestibular pode ser um objetivo com a própria data e o próprio conteúdo programático, ou você usa um objetivo só com as matérias em comum. O plano Gratuito tem um objetivo ativo; o Essencial, até três.': 'Yes. Each exam can be a goal with its own date and syllabus, or you use a single goal with the subjects they share. The Free plan has one active goal; Essential, up to three.',
'Cronograma de estudos para ENEM e vestibular: áreas e matérias como tópicos, meta diária, revisões automáticas, questões e simulados por área. Comece grátis.': 'Study schedule for college entrance exams: areas and subjects as topics, a daily goal, automatic reviews, questions and mock exams per area. Start for free.',
'cronograma de estudos enem, app de estudos para vestibular, plano de estudos enem, app para estudar para o enem, organizar estudos vestibular, simulado enem acompanhamento, rotina de estudos vestibular, planner de estudos enem': 'college entrance exam study schedule, ENEM study planner, high school study planner, entrance exam study routine, mock exam tracker, study schedule app for students',
'Cronograma de estudos para ENEM e vestibular': 'Study schedule for college entrance exams',
'Exemplo ilustrativo de árvore de áreas do ENEM: objetivo, áreas, matérias e materiais': 'Illustrative example of an exam area tree: goal, areas, subjects and materials',
'Rotina de quem faz escola e cursinho': 'Routine of students in school and prep course',
'Exemplo do cartão de ENEM: 40 de 60 minutos registrados, 20 minutos de recuperação sugerida': 'Example of the ENEM card: 40 of 60 minutes logged, 20 minutes of suggested catch-up',
# --- planos ---
'Planos e preços: app de estudos grátis e planos pagos | Estudatta': 'Plans and pricing: free study planner and paid plans | Estudatta',
'Planos e preços: comece grátis, amplie quando precisar.': 'Plans and pricing: start free, upgrade when you need to.',
'O Gratuito cobre um objetivo por inteiro: meta, sessões, saldo e recuperação, revisões, simulados, conquistas e o Tatá. Os planos pagos acrescentam mais objetivos, lembretes e relatórios completos e a IA para organizar o conteúdo e o plano.': 'Free covers one goal in full: target, sessions, balance and catch-up, reviews, mock exams, achievements and Tatá. Paid plans add more goals, full reminders and reports, and AI to organize the content and the plan.',
'Mensal': 'Monthly',
'Anual': 'Yearly',
'Comparação': 'Comparison',
'Gratuito × Essencial × Completo': 'Free × Essential × Complete',
'Comparação entre os planos, conforme o catálogo do serviço': 'Plan comparison, according to the service catalog',
'Recurso': 'Feature',
'Valor mensal': 'Monthly price',
'Valor anual': 'Yearly price',
'Objetivos ativos': 'Active goals',
'Sem limite': 'Unlimited',
'IA: organizar conteúdo, plano e conversar com o Tatá': 'AI: organize content, plan and chat with Tatá',
'10 ações por mês (até 3 por dia)': '10 actions a month (up to 3 a day)',
'60 ações por mês (até 10 por dia)': '60 actions a month (up to 10 a day)',
'200 ações por mês (até 30 por dia)': '200 actions a month (up to 30 a day)',
'Tatá com voz natural': 'Tatá with natural voice',
'20 falas por mês': '20 lines a month',
'300 falas por mês': '300 lines a month',
'1.000 falas por mês': '1,000 lines a month',
'Lembretes': 'Reminders',
'Horário planejado': 'Planned time',
'Completos + resumo por e-mail': 'Full + email summary',
'Relatórios': 'Reports',
'Semana': 'Week',
'Semana, mês e trimestre': 'Week, month and quarter',
'Distribuição automática das tarefas': 'Automatic task distribution',
'Não': 'No',
'Sim': 'Yes',
'20 (até 100 MB)': '20 (up to 100 MB)',
'100 (até 1 GB)': '100 (up to 1 GB)',
'Sem limite (até 5 GB)': 'Unlimited (up to 5 GB)',
'Saldo e recuperação da pendência': 'Balance and catch-up of owed time',
'Simulados e taxa de acerto': 'Mock exams and accuracy',
'Companheiro Tatá': 'Tatá companion',
'Histórico completo das sessões': 'Full session history',
'Exportação dos seus dados': 'Export of your data',
'Valores e limites vêm do catálogo do serviço e podem mudar; o que vale é o que aparece aqui e na tela de planos do app no momento da assinatura.': 'Prices and limits come from the service catalog and may change; what counts is what appears here and on the app’s plans screen at the time of subscribing.',
'Sem letras miúdas': 'No fine print',
'O que vale em qualquer plano': 'What holds on any plan',
'Histórico e exportação nunca dependem de assinatura': 'History and export never depend on a subscription',
'Tudo o que você registrou continua visível e exportável em qualquer plano, inclusive depois de cancelar. Os dados são seus.': 'Everything you logged stays visible and exportable on any plan, including after cancelling. The data is yours.',
'Cancelamento sem obstáculos': 'Cancellation without hurdles',
'Você cancela na tela de planos, dentro do app. Sem ligação, sem formulário de retenção. O acesso ao plano pago vai até o fim do período já pago.': 'You cancel on the plans screen, inside the app. No phone call, no retention form. Access to the paid plan runs until the end of the period already paid.',
'Sem cobrança por minuto': 'No per-minute charges',
'O preço não muda conforme o tempo de estudo, o número de sessões ou de lembretes. Estudar mais não custa mais.': 'The price doesn’t change with study time, number of sessions or reminders. Studying more doesn’t cost more.',
'Perguntas sobre cobrança': 'Billing questions',
'Cobrança, cancelamento e seus dados': 'Billing, cancellation and your data',
'Preciso de cartão para começar?': 'Do I need a card to start?',
'Não. A conta gratuita não pede forma de pagamento. Você só informa dados de pagamento se decidir assinar um plano pago.': 'No. The free account doesn’t ask for a payment method. You only enter payment details if you decide to subscribe to a paid plan.',
'Quanto custam os planos pagos?': 'How much do the paid plans cost?',
'Essencial: R$ 9,90 por mês ou R$ 94,80 por ano. Completo: R$ 19,90 por mês ou R$ 190,80 por ano. Os valores desta página vêm do catálogo do serviço; o que vale é o que aparece na tela de planos do app no momento da assinatura.': 'Essential: R$ 9.90 a month or R$ 94.80 a year. Complete: R$ 19.90 a month or R$ 190.80 a year (prices in Brazilian reais). The prices on this page come from the service catalog; what counts is what appears on the app’s plans screen at the time of subscribing.',
'Quando o plano pago é liberado depois do pagamento?': 'When is the paid plan unlocked after payment?',
'Quando o provedor de pagamento confirma a cobrança. Voltar da página de pagamento, por si só, não libera o plano; a confirmação costuma chegar em instantes e o app atualiza sozinho.': 'When the payment provider confirms the charge. Returning from the payment page alone doesn’t unlock the plan; confirmation usually arrives within moments and the app updates by itself.',
'Como cancelo? O que acontece depois?': 'How do I cancel? What happens next?',
'Na tela de planos do app, em poucos toques. Você continua com o plano pago até o fim do período já pago e depois volta ao Gratuito. Nada é apagado.': 'On the app’s plans screen, in a few taps. You keep the paid plan until the end of the period already paid and then return to Free. Nothing is deleted.',
'Se eu voltar ao Gratuito com vários objetivos, perco algum?': 'If I return to Free with several goals, do I lose any?',
'Não. Nada é apagado. Se houver mais objetivos ativos do que o Gratuito permite, os mais recentes continuam ativos e os demais ficam pausados até você escolher. Histórico, materiais e exportação continuam disponíveis.': 'No. Nothing is deleted. If there are more active goals than Free allows, the most recent stay active and the others are paused until you choose. History, materials and export remain available.',
'Existe cobrança por uso, por minuto ou por lembrete?': 'Are there charges per use, per minute or per reminder?',
'Não. O plano tem um valor fixo por mês ou por ano, o que estiver no catálogo.': 'No. The plan has a fixed price per month or per year, whatever is in the catalog.',
'Há desconto, cupom ou promoção?': 'Are there discounts, coupons or promotions?',
'O único desconto é o do plano anual, que sai 20% mais barato que 12 mensalidades. Não há cupom nem preço promocional por tempo limitado.': 'The only discount is the yearly plan, which is 20% cheaper than 12 monthly payments. There are no coupons or limited-time promotional prices.',
'Outra dúvida sobre pagamento? Escreva para': 'Another billing question? Write to',
'ou use a página de': 'or use the',
'contato': 'contact page',
'Compare os planos do Estudatta: Gratuito para sempre, Essencial por R$ 9,90/mês e Completo por R$ 19,90/mês. Sem cartão para começar e cancelamento livre.': 'Compare Estudatta plans: Free forever, Essential for R$ 9.90/month and Complete for R$ 19.90/month. No card to start and cancel anytime.',
'estudatta preço, app de estudos grátis, planner de estudos gratuito, assinatura app de estudos, plano essencial estudatta, plano completo estudatta': 'estudatta pricing, free study planner, study app subscription, estudatta essential plan, estudatta complete plan',
'Planos e preços do Estudatta: comece grátis': 'Estudatta plans and pricing: start free',
'Período de cobrança': 'Billing period',
# --- faq ---
'Perguntas frequentes sobre o app de estudos | Estudatta': 'Frequently asked questions about the study planner | Estudatta',
'Perguntas frequentes': 'Frequently asked questions',
'Perguntas frequentes: o que o app de estudos faz — e o que não faz.': 'FAQ: what the study app does — and what it doesn’t.',
'O app': 'The app',
'Offline e aparelhos': 'Offline and devices',
'Revisões, simulados e conquistas': 'Reviews, mock exams and achievements',
'Materiais e importação': 'Materials and import',
'Dados e privacidade': 'Data and privacy',
'Planos e cancelamento': 'Plans and cancellation',
'Não. Ele mostra constância e tempo por objetivo. Aprendizado se mede nos seus próprios exercícios, provas e conversas.': 'No. It shows consistency and time per goal. Learning is measured in your own exercises, exams and conversations.',
'Serve só para idiomas e concursos?': 'Is it only for languages and civil service exams?',
'Não. Qualquer estudo ou prática com meta de tempo cabe: vestibular e ENEM, faculdade e residência, certificação, leitura, instrumento. Idiomas e concursos são os casos mais comuns, por isso têm páginas próprias.': 'No. Any studying or practice with a time goal fits: entrance exams, college and residency, certifications, reading, an instrument. Languages and civil service exams are the most common cases, which is why they have their own pages.',
'Revisar, medir e comemorar, sem ranking': 'Review, measure and celebrate, with no leaderboard',
'Depois que você estuda um tópico, o app agenda revisões em 1, 7 e 30 dias. Os intervalos são configuráveis, e as revisões do dia aparecem no plano de hoje.': 'After you study a topic, the app schedules reviews at 1, 7 and 30 days. The intervals are configurable, and the day’s reviews show up in today’s plan.',
'Como registro questões e simulados?': 'How do I log questions and mock exams?',
'Na sessão do tipo questões, informe quantas fez e quantas acertou; o relatório mostra a taxa de acerto por matéria. Simulados são registrados à parte, com os acertos por matéria, e o app mostra a evolução entre eles. As questões e os simulados são os seus: o app não tem banco de questões.': 'In a question-type session, enter how many you did and how many you got right; the report shows accuracy per subject. Mock exams are logged separately, with correct answers per subject, and the app shows the progress between them. The questions and mock exams are yours: the app has no question bank.',
'O que conta para ganhar XP?': 'What counts toward earning XP?',
'Minutos estudados, meta do dia cumprida, questões registradas, revisões feitas e simulados. O XP acumulado define o seu nível, e há mais de 40 conquistas, além de desafios semanais e recordes pessoais.': 'Minutes studied, daily goal met, questions logged, reviews done and mock exams. Accumulated XP sets your level, and there are more than 40 achievements, plus weekly challenges and personal records.',
'Se eu quebrar a sequência, perco conquistas ou XP?': 'If I break my streak, do I lose achievements or XP?',
'Não. O que você conquistou fica com você: conquistas, XP e nível não diminuem. Só a contagem de dias seguidos recomeça. Recuperar 1 hora de tempo pendente, aliás, rende a conquista Retomada.': 'No. What you earned stays with you: achievements, XP and level don’t go down. Only the count of consecutive days restarts. Making up 1 hour of owed time, by the way, earns the Comeback achievement.',
'Existe ranking com outras pessoas?': 'Is there a leaderboard with other people?',
'Não. A comparação é sempre com o seu próprio histórico.': 'No. The comparison is always with your own history.',
'Quem é o Tatá? Dá para desligar?': 'Who is Tatá? Can I turn him off?',
'O Tatá é o mascote do app: um cronômetro pequeno que acompanha a sessão, lendo durante o foco, com uma xícara na pausa, comemorando metas e dormindo nos dias de descanso. Sim, dá para desligar em Preferências.': 'Tatá is the app’s mascot: a little stopwatch that follows your session, reading during focus, holding a cup on breaks, celebrating goals and sleeping on rest days. Yes, you can turn him off in Preferences.',
'Esses recursos estão em quais planos?': 'Which plans include these features?',
'Em todos, inclusive no Gratuito: revisões automáticas, simulados e taxa de acerto, conquistas, níveis e desafios, e o Tatá.': 'All of them, including Free: automatic reviews, mock exams and accuracy, achievements, levels and challenges, and Tatá.',
'Sem internet, no celular e no computador': 'Offline, on phone and computer',
'O que exatamente funciona offline?': 'What exactly works offline?',
'Ver o plano do dia, usar o cronômetro e registrar sessões. Tudo fica salvo no aparelho e sincroniza quando a conexão voltar. Entrar na conta, pagar, enviar arquivos e importar o edital precisam de internet.': 'Viewing the daily plan, using the timer and logging sessions. Everything is saved on the device and syncs when the connection returns. Signing in, paying, uploading files and importing the syllabus need internet.',
'E se eu registrar no celular sem internet e depois no computador?': 'What if I log on my phone offline and then on my computer?',
'Os registros dos dois aparelhos são sincronizados. Quando a mesma informação foi alterada nos dois lados, o app mostra o conflito para você decidir, em vez de escolher sozinho.': 'Logs from both devices are synced. When the same information was changed on both sides, the app shows you the conflict to decide, instead of choosing on its own.',
'Funciona no iPhone?': 'Does it work on iPhone?',
'Sim, pelo Safari. Para receber lembretes no iPhone ou iPad, adicione o app à tela inicial (Compartilhar → Adicionar à Tela de Início) e permita as notificações quando o app pedir. Sem esse passo, o sistema da Apple não entrega notificações de sites.': 'Yes, through Safari. To get reminders on iPhone or iPad, add the app to your home screen (Share → Add to Home Screen) and allow notifications when the app asks. Without that step, Apple’s system doesn’t deliver website notifications.',
'Os lembretes tocam com a tela bloqueada?': 'Do reminders ring with the screen locked?',
'Os lembretes usam notificações do navegador ou do app instalado. No iPhone e iPad, é preciso adicionar o app à tela inicial e permitir notificações. O sistema pode atrasar entregas; não prometemos alarme exato.': 'Reminders use browser or installed-app notifications. On iPhone and iPad, you need to add the app to the home screen and allow notifications. The system may delay deliveries; we don’t promise an exact alarm.',
'PDFs, edital e o que a IA faz': 'PDFs, syllabus and what the AI does',
'Meu PDF é escaneado, sem texto selecionável. A importação funciona?': 'My PDF is scanned, with no selectable text. Does the import work?',
'Não. A importação lê a camada de texto do PDF; quando ela não existe, o app avisa que não conseguiu ler, em vez de inventar uma estrutura. O reconhecimento de texto em imagem (OCR) não está disponível. Cole o texto manualmente ou use o modelo de CSV. Como material de estudo, o PDF escaneado pode ser enviado normalmente, com intervalo de páginas.': 'No. The import reads the PDF’s text layer; when there isn’t one, the app says it couldn’t read it instead of making up a structure. Text recognition from images (OCR) is not available. Paste the text manually or use the CSV template. As study material, a scanned PDF can be uploaded normally, with a page range.',
'O que a IA faz no app?': 'What does the AI do in the app?',
'Todos os planos têm ações de IA: 10 por mês no Gratuito, 60 no Essencial e 200 no Completo. Ela faz quatro coisas, sempre opcionais e só quando você pede: conversar com o Tatá sobre o seu estudo (ele responde com base nos seus dados e nunca inventa números); sugerir a estrutura de matérias e tópicos a partir de um texto ou de uma importação; sugerir uma distribuição do plano; redigir o resumo da semana. Toda resposta é uma prévia: nada muda até você revisar e confirmar.': 'Every plan has AI actions: 10 a month on Free, 60 on Essential and 200 on Complete. It does four things, always optional and only when you ask: chat with Tatá about your studying (he answers from your data and never makes up numbers); suggest the subject and topic structure from a text or an import; suggest a plan distribution; write the weekly summary. Every answer is a preview: nothing changes until you review and confirm.',
'O Tatá fala?': 'Does Tatá talk?',
'Sim. Cada plano tem uma cota mensal de falas com voz natural (20 no Gratuito, 300 no Essencial e 1.000 no Completo). Quando a cota acaba, o Tatá continua falando com a voz do próprio aparelho, sem custo. A voz fica desligada por padrão e você liga quando quiser.': 'Yes. Each plan has a monthly quota of natural-voice lines (20 on Free, 300 on Essential and 1,000 on Complete). When the quota runs out, Tatá keeps talking with the device’s own voice, at no cost. Voice is off by default and you turn it on whenever you like.',
'E o que a IA não faz?': 'And what doesn’t the AI do?',
'Não dá aula, não corrige exercícios, não avalia seu nível, não prevê resultado de prova e não roda em segundo plano. Os recursos de IA podem estar desligados; nesse caso o app informa e você organiza tudo manualmente, sem perder nenhuma função essencial.': 'It doesn’t teach, grade exercises, assess your level, predict exam results or run in the background. AI features may be turned off; in that case the app tells you and you organize everything manually, without losing any essential function.',
'O que é enviado quando uso um recurso de IA?': 'What is sent when I use an AI feature?',
'Apenas o trecho necessário: o texto que você colou ou importou, ou os títulos dos tópicos e os números do período. Seu e-mail, nome e identificadores de conta não são enviados. Os detalhes estão na política de privacidade.': 'Only the necessary excerpt: the text you pasted or imported, or the topic titles and the period’s numbers. Your email, name and account identifiers are not sent. Details are in the privacy policy.',
'Seus dados são seus': 'Your data is yours',
'Quais dados o app guarda?': 'What data does the app keep?',
'Os que você cria — objetivos, metas, sessões, tarefas, materiais — e os necessários para a conta funcionar, como e-mail e sessões de acesso. A lista completa, com finalidade e prazo, está na política de privacidade.': 'What you create — goals, targets, sessions, tasks, materials — and what the account needs to work, such as email and login sessions. The full list, with purpose and retention, is in the privacy policy.',
'Consigo exportar meus dados?': 'Can I export my data?',
'Sim, em qualquer plano e a qualquer momento: todos os seus dados em um arquivo JSON e o histórico de sessões em CSV, que abre em planilhas. A exportação não depende de assinatura.': 'Yes, on any plan and at any time: all your data in a JSON file and the session history in CSV, which opens in spreadsheets. Export doesn’t depend on a subscription.',
'Posso excluir minha conta?': 'Can I delete my account?',
'Sim, pelas configurações do app. Os prazos e o que é apagado estão descritos na política de privacidade.': 'Yes, from the app settings. The timelines and what gets deleted are described in the privacy policy.',
'Vocês vendem dados ou mostram anúncios?': 'Do you sell data or show ads?',
'Não. O serviço se mantém pelas assinaturas dos planos Essencial e Completo. Métricas de uso só são coletadas se você consentir, e a resposta pode ser mudada depois.': 'No. The service is supported by Essential and Complete subscriptions. Usage metrics are only collected if you consent, and the answer can be changed later.',
'Assinar, cancelar e continuar com seus dados': 'Subscribe, cancel and keep your data',
'Posso cancelar quando quiser?': 'Can I cancel whenever I want?',
'Sim. O cancelamento é feito na tela de planos, sem obstáculos. Seu histórico e a exportação dos seus dados continuam disponíveis.': 'Yes. Cancellation is done on the plans screen, with no hurdles. Your history and data export remain available.',
'O que acontece com meus dados depois de cancelar?': 'What happens to my data after I cancel?',
'Nada é apagado. Você volta ao plano Gratuito ao fim do período pago; o histórico continua visível e a exportação continua disponível.': 'Nothing is deleted. You return to the Free plan at the end of the paid period; the history stays visible and export stays available.',
'Preciso de cartão para criar a conta?': 'Do I need a card to create an account?',
'Não. A conta gratuita não pede forma de pagamento.': 'No. The free account doesn’t ask for a payment method.',
'Não achou a resposta? Escreva para': 'Didn’t find the answer? Write to',
'. Planos e limites estão em': '. Plans and limits are on the',
'planos': 'plans page',
'; o tratamento de dados, em': '; data handling is in the',
'privacidade': 'privacy policy',
'Tire dúvidas sobre o Estudatta: como funciona o plano diário, o que acontece quando você não estuda, offline, revisões, simulados, IA, dados e assinatura.': 'Get answers about Estudatta: how the daily plan works, what happens when you don’t study, offline use, reviews, mock exams, AI, data and subscriptions.',
'estudatta perguntas frequentes, como funciona o estudatta, app de estudos offline, app de estudos dúvidas, cancelar assinatura estudatta': 'estudatta faq, how estudatta works, offline study app, study app questions, cancel estudatta subscription',
'Perguntas frequentes sobre o Estudatta': 'Frequently asked questions about Estudatta',
'Temas': 'Topics',
# --- contato ---
'Contato: fale com a equipe do Estudatta': 'Contact: talk to the Estudatta team',
'Fale com a gente.': 'Talk to us.',
'Dúvida, problema ou sugestão: escreva pelo formulário ou direto para': 'A question, a problem or a suggestion: write through the form or directly to',
'Talvez a resposta já esteja nas': 'The answer may already be in the',
'perguntas frequentes': 'FAQ',
'. Sobre o tratamento dos seus dados, veja a': '. About how your data is handled, see the',
'política de privacidade': 'privacy policy',
'Nome (opcional)': 'Name (optional)',
'Assunto': 'Subject',
'Dúvida sobre o app': 'Question about the app',
'Problema técnico': 'Technical problem',
'Planos e cobrança': 'Plans and billing',
'Privacidade e dados': 'Privacy and data',
'Outro assunto': 'Other',
'Mensagem': 'Message',
'de 4000 caracteres. Não envie senhas nem dados de pagamento.': 'of 4000 characters. Don’t send passwords or payment details.',
'Se preferir, escreva para': 'If you prefer, write to',
'Enviar mensagem': 'Send message',
'Mensagem recebida.': 'Message received.',
'Enviar outra mensagem': 'Send another message',
'Fale com a equipe do Estudatta: dúvidas sobre o app de estudos, planos, pagamento ou seus dados. Respondemos por e-mail.': 'Talk to the Estudatta team: questions about the study app, plans, payment or your data. We reply by email.',
'contato estudatta, suporte estudatta, falar com estudatta': 'contact estudatta, estudatta support',
'Contato — Estudatta': 'Contact — Estudatta',
'Formulário de contato': 'Contact form',
}
